apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: platform
    namespace: platform
spec:
    secretTemplates:
        - name: object-storage-root
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SiwaT9zAVIxC,iv:22M4C785iIkLN60UaU9glG6nDENNfGt/hyLaxGdEbEM=,tag:bTql5z8rn8bvKzfevKRZ0A==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z/GGEQ9DzcfrGTJTrQa2SK2Y,iv:dPYezYCpMSmAH5e/Vue4CMDNUd9Vd4GwqbAws/MqpiY=,tag:Lrc4KrVduqI0K2wSj9spxA==,type:str]
            ADMIN_PASSWORD: ENC[AES256_GCM,data:lY9EJRFKW0Lbj56NVxQKEMQvIhVwhW6O,iv:x6pVR3kgGX6z4mB+qYfmx6boiW1xkn6EVv38y0Z1qTw=,tag:b0MphRIRyhoZ1LqK8QVnlQ==,type:str]
        - name: zot-credentials
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:M/b1q3dDPiyy,iv:DpbEHTFXLj3zQTTHvGfz1lKu9LMhvQRRQP24+4PJ8pk=,tag:wwvNHoqnjK6/Adnu3pGL9g==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:a6yvVsttiIgqWg3HrpPBqavr,iv:NhO8eKSCWnGhGEU+BiaKpC7ySKMizTHNZOGG77Jm7sg=,tag:cJuzQ18Qxafi8Lksn1E6RA==,type:str]
            htpasswd: ENC[AES256_GCM,data:WPU1MgGOu0rOZNjgFxyJ/45m0umYUpVUtASCT9853ExekVAAunasnT+WTxmgYJSTlHuJuRfqtAL960+GN7AZQYTCKJ0EWGVfjxE0OpMBBG82h/CQ76VjZoACopwEWIV4VYOKRdKeXsdAZmwxm5HNVSwVGIydzwYO8+z0bOcIPoSz8IoNOQ==,iv:pnvJOQbqCh5/cT1M0c73KtEzZnAXq+MaWmmQBvhdfQw=,tag:TnlNdbOPuQoiCKvcD5kwiQ==,type:str]
        - name: observability-bucket
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zhuAKIs54rJv,iv:sl6A3Cy+srCF7n/0WD7+5+7KSJBws9zI2OSFZ90i798=,tag:J5b/KP1/ZZrZCjrOls7Itg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DCH7DTYgebIuJY4cE1CybnWG,iv:lc+akIcGsHFxWQibb8Fq896e5QBOl6yhF/sBRY/h4JM=,tag:/1Zsfgs+mXnSZQUPstf1EA==,type:str]
        - name: postgres-readonly
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:VQkPnCY/rn0=,iv:XcP/UjWgIa7knT+zpkkbTHI7q4W4Mrjv8SyD7f/afXs=,tag:y6+oVWJW3dGYZDVF78mPzQ==,type:str]
            password: ENC[AES256_GCM,data:HB0FQfHsEj8=,iv:KUFKw6oEwry3InRR48IgMMSxk7ikPQsIGOOW3NPNhXI=,tag:jAPtNRd58Jm18IsG2dcvrw==,type:str]
        - name: postgres-superuser
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:EVpa,iv:t+9I7GRrJZvUQAMFXYrhdEFSDWUahEYlIkIU9jZSnts=,tag:9cJaMLi2UhT7a1wI/v97Hg==,type:str]
            password: ENC[AES256_GCM,data:jAi9,iv:o+cFhOf4PwiY8SFV337Hn5CS28+ECE+YDAKhP9c6q8c=,tag:HdVkGEMhpoKcr4JLrL4mmQ==,type:str]
        - name: temporal-db-creds
          stringData:
            password: ENC[AES256_GCM,data:FuKH,iv:I9c2i9En61jGNfaL7NTTTluvJNKGYUX99IXcbCijseI=,tag:RHNvX5uzrdA3uJTusNWt+w==,type:str]
        - name: openfga-creds
          stringData:
            preshared_key: ENC[AES256_GCM,data:BdpxopCjtgO08Ms=,iv:0kPdTNifjkeV52hHrYVNRBYRGN9W1iBq/Vaey5QRtcU=,tag:Q/X8+2fjlBrlmrg8qo50+A==,type:str]
            datastore_uri: ENC[AES256_GCM,data:8qg6VskucRB8kidbc3qMDs6pTWBrPxVtAwobkmw+IwpLDyQ3KCJGURkFilqfTOQjL3EzhWmBqgoT9rFYkosnSk13nQUQ/P9my0v/WAkNvA86DA2Dtk0=,iv:LCZShgx21GDPwvj/eWU9bZENtiiddX+fftfCmcZdWjw=,tag:BnI/+S6bWW5LXyMG+xKoqA==,type:str]
        - name: catalog-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:2GmbrMUuYseeciZIBQI3JwsK3I1Wl0o4sWMnjlDO7/iG/+fH3wQLMh00bX7Xt0Tb0eAZNJIuECj8LSG3o30ZE0Gj+Ok/J9lZ3MOh77G0Otbt5B8l4Zs=,iv:81znVvkTalyU8/q/oiJhqY9C9g4M53eyF6ucLWg+h2k=,tag:ym2G5yUnf6h/p0ZrHR7gcg==,type:str]
        - name: orders-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:r0ynZM+6Q9jsBZucrzk4keZrfzMU8f6vl5kuyGXZOzq6s75bbFmK24t7zMU6KhJTGt3kyk/5La7w/zU+HNJbDXlyUGu/zfag+qQq6LRx9ew56BFM+Q==,iv:tCRfe/85jKW9EQ4MzAEERlyKGw9x4JgpTgSHt38zUTI=,tag:U2iYtXVDCmVNBnYhSoSb8Q==,type:str]
        - name: orgs-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:HQkPR0QF40l2silhFNGHJNY2YXVdMvHUtE0ZkmJMdkIVLEdAD3us6XTba7C5uv8Nfa75zx5joOz4KBwlAgmJiUm1pG/rNpk8F5ADLyqVHAnbons=,iv:KE8DmX/XabWQmypWZrFc5JIxvoyaFiRtLiuVVzlshyc=,tag:2rrpDdhlPW3fo7doaLdPTA==,type:str]
        - name: payment-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:I9IUwSc38d+yrJSnSq2f3WC2TAnFU8COuWreTNdHW4EtdDQr/9adl4BIqdkhx5mfRbQGPW58IicD79w5WTbeUj+GtE5oJWNE9yb68owae/Lj5SmhM60=,iv:uXu2U91NTiMiwVOChYr+L/A/9FeIbBwQ3yWzJFgyiiM=,tag:Vi/5OV67tkfpkwIdPIlIzw==,type:str]
        - name: kratos-secrets
          stringData:
            secretsDefault: ENC[AES256_GCM,data:QU//QxMJ+gQ/qIZaBn49PYcCdPvajkr4HkOP8mdOwg==,iv:4x0Q9jMxjhzG1pRLnmnG8VGCtMUkhguSPSn4jC7SWLE=,tag:Ikw6dHdNw/j/cJSGlP7OuQ==,type:str]
            secretsCookie: ENC[AES256_GCM,data:aqudDuTsgf5/BJhmge2aWDvwu+iTfL7S+0j5EkUVSMtSJWQ3LVJMTw==,iv:V4ZXsZj1Vo9k3N2iTZUDA7HuDVH1yHhHlF9+Fv4PT9I=,tag:Lid6SvrsAjc60ABU4O3V/w==,type:str]
            secretsCipher: ENC[AES256_GCM,data:PFkepagbOybuXK7tRt8o4gS3igwa4DmmSzenzijJaP8=,iv:KzYrLC3h/WfRTZbtj29JOmUSidE3appofjkoA5fXWQ4=,tag:eKfE2m1/KAlPyfJ5MK3XaQ==,type:str]
            dsn: ENC[AES256_GCM,data:zHTxMta2bncs22YXIwWU8lHU5X0mB2EIigaRyZv81Te67AOKq3SvZr32tdP5IVJ17TMbuTLy2fI05U+pp33qzt9cSZy7IGAeYgErYT1wQmFuU3K5MA==,iv:FOb71HUrxZ7t/7/9XWSME5JtAp5hGodS/q5hBV195Co=,tag:FmMO6TRZe5TARkZI6EUStA==,type:str]
            smtpConnectionURI: ENC[AES256_GCM,data:nL6Rqol0+nWXLBi7k5tkuZB4UOME5M3XmPq3mITgKfgp/8D9gxbJq4bZjBec6VZ/GtwHhJyBRUFVcGQTbWGFPyyAfKiF,iv:d/5qvAJg1K87odJ3QV0vASfuFEoN+ZMkdvvoaclklGo=,tag:ZEjgG+QvO84jWDE/UPc5xA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZXhkQm4vc1BEcmNOUWFw
            WTJXMUlBVloraTY2aDlDS3VaRmFWNzJpM2w0ClpGcWdmeWgwTXd1KytIbzN4cmdC
            WGx1UnRORE9yaWFPVE04NGZhclFGcWMKLS0tIG0vR1prZEM0TEtUc2xPN1JyckhO
            UjUxMkhNNk41TENsd0x5NmJMTHQrTkkKbFXncFljiIXStpNDKi8g4rAqjIamwwZC
            pSDKqzZpqzbcwo6iKwQEZpAdj7t+5jRq3dM5wNbaQmrFr9VSk5ZxBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aapmzzzcs8qm2n9exkel8vtknqsmy9t3k9g99wpypfez8av4uaps0f9gpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T16:51:58Z"
    mac: ENC[AES256_GCM,data:52CdYvCRa/EQmSDTLWK3LhwumpNoPnP3/IMGnTS2lpOXN3X9VHRjPYEYCUspo87k1AH9DN4UAMTlpX7CJsTpf/oRXWQ3N/d9ZGakPPgmaymmQ0zKw9ANZQjompdriQ76FoxhG4HnzneUk8T9vRvsvxKBLWxAeJ/E86wNQT030tM=,iv:kJ+WAeZH80emVFH5AwchNv41ZZJKNXl0NtidV3+bzO0=,tag:s0Jszt6FqQYxFUTWKtyjGA==,type:str]
    version: 3.13.1
