apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: platform
    namespace: platform
spec:
    secretTemplates:
        - name: object-storage-root
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:27NOBZNmusA8,iv:4HelRpLgI+kUJFWVteG+3bBypnkaT3FccWv20ax+7+Q=,tag:oYLr5Kn9xg4ul0MN37t07Q==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:s4rFXaf5BtfA6HCmffn8YLKC,iv:whA9HEfH0HEjkxJCCwxQU9QHOa0QltyDT/fu32TuNxU=,tag:nJaOKbK6eiDtGLCYCh0fUA==,type:str]
            ADMIN_PASSWORD: ENC[AES256_GCM,data:iiA0KJuFZkw2auhV3qQKk8JmW9XhtwCP,iv:QGBYEiVaW9/7t1Z3IluH7S0Lj9EsgN9GBZEAtX4KH2U=,tag:5voFwigy9mvGIxPL9yLo1A==,type:str]
        - name: zot-credentials
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:27NOBZNmusA8,iv:4HelRpLgI+kUJFWVteG+3bBypnkaT3FccWv20ax+7+Q=,tag:oYLr5Kn9xg4ul0MN37t07Q==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:s4rFXaf5BtfA6HCmffn8YLKC,iv:whA9HEfH0HEjkxJCCwxQU9QHOa0QltyDT/fu32TuNxU=,tag:nJaOKbK6eiDtGLCYCh0fUA==,type:str]
            htpasswd: ENC[AES256_GCM,data:JcrOUbWz50XhvwewRyCUoT3x5PIZBXMlzG7u8UgLdjEM759IuDWPVKbIotScdoH9uYxLMnjx1CHsTri9hUxpHfvtaLC2g7Z6N2olRudBXCl7b376zYGG4zRolsA6xFXtI9ywCqYomCUbV4Kqtz1C2ruNPNyNpjYE6q72CxhMj74hhhytXw==,iv:3Vh+DfnMRzOUYjO2FjqqQNIKjH6qBFB8M2xonzzl7V4=,tag:s6epwMFPGyjWVlxsvVPlAA==,type:str]
            consoleAuthorization: ENC[AES256_GCM,data:OVNBMLMZz2HAq4Pk6ifBPq3o0eHwEfyd1s4IoKpbecGobbQdoRwoYjBj,iv:wCihaqBwY3Wr5dJEqQm2qBssA4br8TgBnak6O6h0J7E=,tag:ueob5vJj7Ts9UEVQTfoPKA==,type:str]
        - name: observability-bucket
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:27NOBZNmusA8,iv:4HelRpLgI+kUJFWVteG+3bBypnkaT3FccWv20ax+7+Q=,tag:oYLr5Kn9xg4ul0MN37t07Q==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:s4rFXaf5BtfA6HCmffn8YLKC,iv:whA9HEfH0HEjkxJCCwxQU9QHOa0QltyDT/fu32TuNxU=,tag:nJaOKbK6eiDtGLCYCh0fUA==,type:str]
        - name: postgres-readonly
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:/3OjGD1/GMk=,iv:w01+dHffkWDn8v6EJ2zFT9+60Eec6DDsg8tADSLCRX8=,tag:0hKY89CwSuThf3QkYH0JcQ==,type:str]
            password: ENC[AES256_GCM,data:i2/aM6eou+Y=,iv:6Gzj+H6ZwgPZ3ZLk9ylV37yARMnsamTpGZId5lMStzk=,tag:q6ZO98poNAH1bDJ1iIG9EQ==,type:str]
        - name: postgres-superuser
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:PL+B,iv:kGnwPlhE82zFiiPyx3AjIZ4ADfBe07Gzq8AFgbltScw=,tag:D1K+jhfyT7goVm+OhVFGSQ==,type:str]
            password: ENC[AES256_GCM,data:GJp0,iv:aAy6v2ysWy9+wqSuBnTcpqU6nZO6jwlB1Ptv+1hLWlY=,tag:e0hjiRx6TGUXFMcD3eA72Q==,type:str]
        - name: temporal-db-creds
          stringData:
            password: ENC[AES256_GCM,data:GJp0,iv:aAy6v2ysWy9+wqSuBnTcpqU6nZO6jwlB1Ptv+1hLWlY=,tag:e0hjiRx6TGUXFMcD3eA72Q==,type:str]
        - name: openfga-creds
          stringData:
            preshared_key: ENC[AES256_GCM,data:WR7NFnMesvrn1pc=,iv:aGWVdeZsbgZNgIwJpZdV6KSACDIVY7ujIwILIctbohQ=,tag:fh6WPBoozYqywRrgO3ydzw==,type:str]
            datastore_uri: ENC[AES256_GCM,data:p+g5/t5kJoXr2mlC9pPiiS1kTYH8iqT8wNiLlZVbcRBRPE9XWX8AS6Jfn0LY9A/skXKko3axAwvjcrO1YqAzj5T6dLRq0m+Cd7qGCAh3Gi/EOT2Fsu4=,iv:OWTXeXeNhCEble1mfDWxUKYstVl3mKyhCYx3oCxOdpg=,tag:sXAjlpTWb1QmCCLbEB5zQg==,type:str]
        - name: analytics-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:9hOnB4ot8R9q1sINb6S+yMX1C+bh44LYGLtP+8TudLiBJXG54elw58ijwhdUkJBAwUAjMDrUad7lXabuZsceU36eiu6PVESSn/F0LTqnqqW+SKKZium0BQ==,iv:KeWf7e+EM5kOG9Duvp8C9Huo9Dd0tfKtW+oxBp2wjCI=,tag:kR2QICypZ+qPrgFt4lmNSw==,type:str]
        - name: catalog-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:TrCPXdslqtNunPS0Tu203D36NeKZjhnoBj2BhS2CKRt1uU9Isuu3oVA/oOWuE9g1Tc2lfiZKU+UyFDZvG2RrxA3PVI5wzoPzeMAgSqb0WfszmAXxTFE=,iv:XKWAKNQs6mXNoreMwGFF8kmlCgzsFW8qLoG7x/03eDo=,tag:MYIsbHJ1MYop42LlHuojcw==,type:str]
        - name: orders-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:J9pYvPdlFSEt6fiTFJetuKxedqTxjjNQN5XidU7mwrrX0j7DitV3CwT55NCeQIJDStVLqIB52zYm/XJOLvdhLpwJQhgzN7YJL05p9+Vb7z0wp9dCMg==,iv:HaT5cvk4fjeKDiM22Jk2/O3+q38qMp4REs7j4yK63N4=,tag:/Ynk9TmhYc3oYmyEFyKYuA==,type:str]
        - name: orgs-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:ZlLxh+M8gjqQl53jXmWZ6yycC2nTa4ey1dabQ5D9gTMo9sHS6ZUSYSMamLmN2WEmrT5dgLfJYe8YNfa4ucLDV6eXif4WBly8vKQixtlwJzm/yKE=,iv:2o1rFIheG35fi1zE2AAv5KX9DuCHGhxeLXzXVfNdp3M=,tag:uZWdAvieiIYmv2cXY+EanQ==,type:str]
        - name: payment-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:HV9xc55aq5mg+UISZKfsONZQJTLKGw/eG2XVybTbhzvuyFP3u68mZJmW4aVDCE1ZRQuSr4razxhaBC5yWVDOYRhF5NA5pTL6zIwiVZ4ryoGyGSH9HKw=,iv:T62glTgoH+Hlm/8JJZdNQjcnOW3KIHZz89Yg9UYteXA=,tag:NkYmuj7a5A+FNBdbnAaW3g==,type:str]
        - name: kratos-secrets
          stringData:
            secretsDefault: ENC[AES256_GCM,data:yhZzKeVmPL1gchs5E8gOWmv6HFAk84/MZ9CVoRl1Dg==,iv:8BKUe/wULiJ1/2f5Y1Ha8YB7IMrjtXIAZ7fW/1YNWtA=,tag:3m63tdqNFMd5qmDECBvaqw==,type:str]
            secretsCookie: ENC[AES256_GCM,data:Z7QC/OKNAm5uBq8j0PPJ31Hz0FeHUne1sRERd5A4UE1epqm4g4Dp2A==,iv:JuaCBOhYxrGYkDry1C09RMgkBZ9imyS/xN5h+YIFQQc=,tag:0Pd9H60BJc2gFSy6iMozNA==,type:str]
            secretsCipher: ENC[AES256_GCM,data:RjR+i388naIGIKiVfMUxsVXU8+wsgbyAu3hdiJV6rvg=,iv:Zj5YeKQg+Ahit0sUrLmsRXtUKtxJwS9/pbiEHQs9+aY=,tag:YbskcPOyc+5lgJqAMiJegQ==,type:str]
            dsn: ENC[AES256_GCM,data:xbKdgm1D0tjFsOvhO9i0oYAE24LFZiBJGmx4qEk7Cj7voGE/tnHMTj5mFailVO/Smmpa+K1L8B760BFcS5GaAz6gY5Kfjhm0LBvTxnL+0hXUGeq2xg==,iv:Xbs7AFCbCd6C9YcfpxK62Edi1m6OR3SID//TtXMo1xI=,tag:jjrRyFMxAlfZDPc52vjiqg==,type:str]
            smtpConnectionURI: ENC[AES256_GCM,data:6yFqjTqOF4eUHvZH5Q8REyC7oR3UssiPtHAaGoHrsam+zlTa9vLJgqboPszNdlFK7BMmDGCFhOmYj0fyLMhACRDpL1av,iv:yvxBPv+b0QaQAwJFsbXl3AKWxQnxpt++Qrs34qaocko=,tag:MvXn0nhb9X4Q4aVARL0GSw==,type:str]
        - name: hydra-secrets
          stringData:
            secretsSystem: ENC[AES256_GCM,data:0b2Tnaajy9wb+vfljPyzeFnMyFfZm9DzyIwQvaU/9UdHxrg8i/wV534=,iv:VwjQjxnSdLavvtI2Y1XT395h5TN0AdtIcZa3jXuKFeI=,tag:SWjhA6NFsNaqAFa0PMRjuQ==,type:str]
            secretsCookie: ENC[AES256_GCM,data:mWALUwEcOHkuaIEE1hXPeGtQ6slJR3qGJZPOTLmkBwLBdvtFlRSbw8c=,iv:Zi0YWa7Ut1H27xVhWlHjRcumjY7Di6Ldu/B2en+QG4o=,tag:VAUtjF9L8QrluuwLZaK3UA==,type:str]
            dsn: ENC[AES256_GCM,data:oDHHsOoJldBfIeTkpHiinVmbwS1cxC/JJrZabxHeNdJY18mkOnowzi0mNNRbLyOe6VLH1W/btVJZx26lHsHuUWwmfsbcq4WQzEPWrzzMRWjA49n/,iv:eJ6Hyfq6nGZTTflJULL8QJwOZJyB/VALWrb8Y/V/8B4=,tag:b62TKbqvjd6kmWFTUgZbuA==,type:str]
        - name: postgres-backup-creds
          type: Opaque
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:ef9OP4TX3HBO,iv:BWj8mqfCQtCEov8mRGnJO6Z7cAAo3cIX2qJXjWuuAxY=,tag:SWxPnIhhtKKE+/Y/sD+Qzg==,type:str]
            SECRET_ACCESS_KEY: ENC[AES256_GCM,data:puWGd00EQEerFMmzCM9A50Or,iv:rA24vDOWqudu2eQe0WOb9rZTQRvVHTqIgzTO91hJXpo=,tag:2qkYvrPp1KldEFuPKMGudg==,type:str]
        - name: first-operator
          stringData:
            email: ENC[AES256_GCM,data:wvrYo6U9alnxPDbpR1BmCTlC,iv:h+XIPt/bqV5fX+Ke77VOxhaMXQI4ofOfF9ZSSfoS7V8=,tag:CoOUUa2bvuPmn+lwYL0u/g==,type:str]
            password: ENC[AES256_GCM,data:8xobMViG8DVC+r7OLQ==,iv:TL5NvymKJv4juJQnw1DE2AQWan0p3qpy2bxSZv9P9JI=,tag:D8QVD4slg6GyNJV7jZDJHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R2tPTUMvVGxzT0t4aWlt
            VU8xcDRha2NMMzc0blc2ZDdYMVUyWDVtUVc0CkUzSG1QcE1ZV0s4ZkRJZE9qSERj
            UWpOK2VkUENyVVNBVEhHVERxb3dxencKLS0tIGlDWUp3N29YUGRPMHVxb01xV0Q0
            NW1JYWRGcHhzVG9UT0hZeFBTaG1BR28KRuP41zO6Vk1/7W+yfoyTeHhXtbanM6n2
            f1mO+jw4crmobctoAv9JDyJaZYDdcIxIdSo7yIBV18xoiT3uEyxyuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aapmzzzcs8qm2n9exkel8vtknqsmy9t3k9g99wpypfez8av4uaps0f9gpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T14:50:27Z"
    mac: ENC[AES256_GCM,data:FEb9WSKwJc5YxfWubGWvkAfWWH9/tdDs//J92h0B3qcu3ZPGmYqYBRqEUV0swm8HDX6wQhLPBsdJDH//w9bfBjqLLMq8MVA3MttC4YHsok564OWMmmG+dF5TIGY9XrrQQXPwiCZm6MI5qHTwHcdOMfQx9hugBlquEOJHqsLJm0A=,iv:X+q5eOOw6JPZ6vpgEWUTGShvD+WhwPM3qFIVdlKhXoM=,tag:8MCA4MYxks6ommIKbt6nvw==,type:str]
    version: 3.13.1
