apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: platform
    namespace: platform
spec:
    secretTemplates:
        - name: observability-bucket
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JYm2lGg=,iv:0A0JGIgwIGJi4aH6kfDb5djIP/4M4lJWJ2GL1TrFMh8=,tag:atj9vSyq2eicphJ4VqGbpQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gb+PmMf2MostcRQBx/StTHFv,iv:+6HsK1Hb+ECdfio3HsScUg1yxsz58RG+vJWVJ1iNhyY=,tag:1Dbi3HblAo2eCX8Rs3bs1w==,type:str]
        - name: postgres-superuser
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:pbqe,iv:wT/H4AjW3HP+j9rfXCgSCSXIeEVPup23PWYF0Y44zd8=,tag:5gV1TFEv6gws/8Lyj0eVSg==,type:str]
            password: ENC[AES256_GCM,data:EAU1,iv:bytbxBPvF7tn6qXWLoC1TamJm8k/NO59LL757oNRWaY=,tag:tGDRzBAe4opN4z5l+i0B3A==,type:str]
        - name: temporal-db-creds
          stringData:
            password: ENC[AES256_GCM,data:1Tb3,iv:c4jyAKyUMqa3nmBXoDHhq8ocRutxsRDjHkw7PCKhBHc=,tag:hsm+30RNQsZ6fekK8HKcRg==,type:str]
        - name: spicedb-creds
          stringData:
            preshared_key: ENC[AES256_GCM,data:WZr2S4P5GweKAY8=,iv:zhB5x+fvv6RjonZptJ3pnCFg3a6s0YwsflPAJkRsNXY=,tag:ekYMVlkSoA2cF9HFoAQ+Yw==,type:str]
            datastore_uri: ENC[AES256_GCM,data:AUkSi7V4rBnzNILFT+Kl1eEX/t5TsLMA7X2oT9aWVrX+WkJGBVlD4SZimx+fdN4v7Nk3mkULFXat+wgJZQfcyb7M3EZA81exWneUMZtaZShfMQJz2jQ=,iv:l09ZyELMGm52Ol7+kCjAqW6+DvVPWOt/zZLIMKsgzso=,tag:H7Az1gAGqfdnNBVJThgczg==,type:str]
        - name: catalog-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:lWcG2Ikos27d8xFnScqeLPntJx0PugmuQF25ZspJXthhdKIzCox/8GKe2/6ZxK7qGi/mZj4wzGw0gRdsNY7Fupk3c8/+5ux5lbhbBmHv/NkTdYIjpcs=,iv:l8dzrvUVOM02aUJwYkWqDfNIqR9CqZSQ1mco7ezSQnU=,tag:voO+axqbXItBbaWyHSXpQQ==,type:str]
        - name: orders-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:OPjiHnBJhTnrZXEHSRg6j5CF0+xfoSJKBkJoEwGGKB13OQtVP49CWs+wAYQfwvRx17JJ6rK3X/Vg5K06/psQKpmnX4dGJh4Lq2hm5dD5PwREWZXECA==,iv:jDTO1uD32RT25VRDE1Krql2HI8rULr/5GjqfWgNOvzU=,tag:tfdcBWkSqpyDQm4IKdVwnQ==,type:str]
        - name: orgs-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:Mm6BJulbXz/DoCzDDblZGeO3h6kY3XN18jbQwUJt1BIb2fCz9QsA7CR+hJE02bd8daSKnHJzrsoHFHFGRCj9jW2HAuP216479ppmQqKWY4P26fg=,iv:UObdnMrSDMfJ1HBJhj8+gL/3EH4tBBwlGc5X80EO7uw=,tag:QLw3MD1KCI18grDr1X4FyA==,type:str]
        - name: payment-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:hO8H65/VykG5bR1257nFe/HJ0oS8MlhIZRqJGRaZ49JOyVokzATDcWSfEv6qZ8QK5hQc6m57y7HulSGxD4KLr1eJhLxkEAtttEA1R4zQhkTN36PCLiY=,iv:5IejryGyo4zJZMTId+wx/mzwXuC7IujgNfD1zCen/3M=,tag:cccy0nAyICfCBnHKKQwipQ==,type:str]
        - name: kratos-secrets
          stringData:
            secretsDefault: ENC[AES256_GCM,data:BGbn0Yl03s5LsQHiahix+8yc2OCPGg0vH9A9HgOATA==,iv:oGFDvZyQDFeqvlcJc3rlSygAb49trhE/umwGp+cbRnY=,tag:blOJrCj/KbZJOFVcAjdC/w==,type:str]
            secretsCookie: ENC[AES256_GCM,data:zYDCkQebiAsYUEZcFYvSL/D8lNmEUQLroIyW08hHdq0nyJTWQhSj/A==,iv:cZuXS+J2Ne+smDZpAKdGOIvAvHyv5gABSLf+/A5S9A8=,tag:/9US7MtwShJXm2+zZEpYMQ==,type:str]
            secretsCipher: ENC[AES256_GCM,data:ouHeHKU74cQi07XIRD+ISO5KvwvmIDPPmjO4YaS9WNE=,iv:RzC4qEI942p/lUX1kkzi6w/ZtRzfFKXjsczIm6e2WMU=,tag:r8Iqx+kVaUqbpOX9XwljyA==,type:str]
            dsn: ENC[AES256_GCM,data:GK5+yK8hYDHz/OVUn/l4k6943APbTz2FhRrONCk8M3JXwg6QVdJat/26eOTnxnU7MJTiDJaCe3LZ2Ov+Kf6xWDxk5LyAS9Yt5bCpySDG7XRRSTQUPw==,iv:WqYV38EUUAixxvL+GFkt20nfj/14wlKXzraWhF/GR9c=,tag:EgnCoQFXJBVpqtu91K6yqg==,type:str]
            smtpConnectionURI: ENC[AES256_GCM,data:zROE7FKge7CjcGBCBJ8YonbndHfkHqAjsfGsBe+FDFEp/lk75h5yQM3BOpZSuDCleKGua2yD,iv:t19PYTE1GLbUlTy+eRUY9wdHWR+ermhe5sB7ghValOM=,tag:YJc+7ZJothuvfYakDlK4Qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad3V4Tll4S2Jzcm0wZXZx
            Q3BTWGgrUXEvclNJbWFaS1pUbWIvYWF6enk0Cjd2dHJLNGs1VjVwNCtDcGxReGtX
            Y2lwdm4zTDdYanpDU0VWVXhMQmduR2cKLS0tIElYYng0WFM1c2lBV21jNUIyZDdp
            Y29ZS3JlditTTGhWTU9RSk15b3ZFdWMK4B9BnLHa1Efg13t5WTnZp72sZ4/2ybHg
            170yAOdPBYl/k5eJ5Ta7/fA+vB57ziSe1ZfA+xfB9F8K02V9xTObAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aapmzzzcs8qm2n9exkel8vtknqsmy9t3k9g99wpypfez8av4uaps0f9gpp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T13:47:39Z"
    mac: ENC[AES256_GCM,data:pO/BEusr/BK2LlALq43qQ8sZOZeMf9JqIyoMTfxt2izTlUn+w5DjcUoFWko9u8HX84tb7aW+kR9/aQ1eX0Y+r8vkKnOvhOKxT4p0rh/zFItK1bo26gfo6vPMtHS4Lb6Pg6nAItNQmhY82/fGek0udFaJnnjF7q6lNwPDZjrv26s=,iv:NxT3Fcy/fLAgAbpo46QJpCuylpO32bYGdQHwA3br0ho=,tag:G7n1irBeAGTvWve4DvlPWQ==,type:str]
    version: 3.13.1
