// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         pgtype.UUID        `json:"id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	Quantity   int32              `json:"quantity"`
	TotalCents int32              `json:"total_cents"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
