// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// pii:identifier
	OwnerID pgtype.Text `json:"owner_id"`
	// pii:none
	OrgID pgtype.UUID `json:"org_id"`
	// pii:none
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	// pii:none
	Total pgtype.Numeric `json:"total"`
	// pii:none
	Currency string `json:"currency"`
}
