// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
insert into orders (product_id, quantity, total_cents, status)
values ($1, $2, $3, 'pending')
returning id, product_id, quantity, total_cents, status
`

type CreateOrderParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	Quantity   int32       `json:"quantity"`
	TotalCents int32       `json:"total_cents"`
}

type CreateOrderRow struct {
	ID         pgtype.UUID `json:"id"`
	ProductID  pgtype.UUID `json:"product_id"`
	Quantity   int32       `json:"quantity"`
	TotalCents int32       `json:"total_cents"`
	Status     string      `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.ProductID, arg.Quantity, arg.TotalCents)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Quantity,
		&i.TotalCents,
		&i.Status,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
select
  id,
  product_id,
  quantity,
  total_cents,
  status
from orders
where id = $1
`

type GetOrderRow struct {
	ID         pgtype.UUID `json:"id"`
	ProductID  pgtype.UUID `json:"product_id"`
	Quantity   int32       `json:"quantity"`
	TotalCents int32       `json:"total_cents"`
	Status     string      `json:"status"`
}

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Quantity,
		&i.TotalCents,
		&i.Status,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
update orders set status = $2
where id = $1
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
