// Code generated by ogen, DO NOT EDIT.

package payment

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateChargeOperation OperationName = "CreateCharge"
	GetChargeOperation    OperationName = "GetCharge"
)
