// Code generated by ogen, DO NOT EDIT.

package payment

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateCharge implements createCharge operation.
//
// Starts the Charge Temporal workflow. Idempotent on Idempotency-Key header. Returns a workflow handle
// (ADR-0006).
//
// POST /charges
func (UnimplementedHandler) CreateCharge(ctx context.Context, req *ChargeInput, params CreateChargeParams) (r *WorkflowHandle, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCharge implements getCharge operation.
//
// Fetch a charge by id.
//
// GET /charges/{id}
func (UnimplementedHandler) GetCharge(ctx context.Context, params GetChargeParams) (r *Charge, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
