// Code generated by ogen, DO NOT EDIT.

package payment

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreateChargeParams is parameters of createCharge operation.
type CreateChargeParams struct {
	// Client-generated key that makes the charge request idempotent.
	IdempotencyKey string
}

func unpackCreateChargeParams(packed middleware.Parameters) (params CreateChargeParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	return params
}

func decodeCreateChargeParams(args [0]string, argsEscaped bool, r *http.Request) (params CreateChargeParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// GetChargeParams is parameters of getCharge operation.
type GetChargeParams struct {
	// Charge id.
	ID string
}

func unpackGetChargeParams(packed middleware.Parameters) (params GetChargeParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeGetChargeParams(args [1]string, argsEscaped bool, r *http.Request) (params GetChargeParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
