/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analytics/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Record a batch of marketing events. */
        post: operations["recordEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Event counts over a window, the aggregate every funnel question starts from. */
        get: operations["summariseEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/funnels/{funnel}/rollup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read a funnel's computed rollup, in bucket then step order. */
        get: operations["getFunnelRollup"];
        put?: never;
        /**
         * @description Recompute a funnel's rollup over a window, one bucket per day.
         *
         *     Idempotent by construction: a bucket is replaced rather than added to, so
         *     re-running over a window that is still filling is the normal case rather
         *     than a hazard. The most recent bucket is always incomplete.
         */
        post: operations["computeFunnelRollup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read the recorded decision for a session. */
        get: operations["getConsent"];
        /** @description Record or withdraw consent for a session. */
        put: operations["recordConsent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457 problem details. Served as `application/problem+json` by services and
         *     by the edge alike, so a generated client has one error branch rather than two.
         * @example {
         *       "type": "about:blank",
         *       "title": "Not Found",
         *       "status": 404,
         *       "detail": "No product with that identifier.",
         *       "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736"
         *     }
         */
        Problem: {
            /**
             * @description `about:blank`, except where two errors share a status code and a client
             *     handles them differently. That case takes a `urn:problem-type:<service>:<slug>`
             *     URN — never a dereferenceable URL, which would put an error taxonomy into
             *     the flat public URL namespace.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * @description A stable, human-readable summary. Does not vary with the instance.
             * @example Not Found
             */
            title: string;
            /**
             * @description The HTTP status, duplicated in the body.
             * @example 404
             */
            status: number;
            /**
             * @description Instance-specific and safe to show a user. Never a stack trace, a query, or
             *     an internal hostname.
             * @example No product with that identifier.
             */
            detail?: string;
            /**
             * @description The W3C Trace Context trace-id of the failing request, so a user-reported
             *     error reaches its trace. Supplied from the active span, not by the handler.
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string;
            /**
             * @description Field-level validation failures, populated from the generated validator.
             *     Absent when the failure is not a validation failure.
             */
            errors?: {
                /**
                 * @description RFC 6901 JSON Pointer to the offending member.
                 * @example /price/amount
                 */
                pointer: string;
                /** @example must be a decimal amount */
                message: string;
            }[];
        };
        /** @description A batch of marketing events from one session. */
        EventBatch: {
            session_id: string;
            identity_id?: string;
            /** @enum {string} */
            device_class?: "mobile" | "tablet" | "desktop" | "unknown";
            events: components["schemas"]["Event"][];
        };
        /** @description One marketing event. The name carries no `marketing.` prefix — that is how the collector routed it, not what it is. */
        Event: {
            name: string;
            /** Format: date-time */
            occurred_at: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description How many events of the batch were stored.
         * @example {
         *       "stored": 3,
         *       "dropped": 0
         *     }
         */
        RecordResult: {
            stored: number;
            /** @description Events discarded for want of a recorded grant. A non-zero value here is a client emitting without consent, which is worth seeing. */
            dropped: number;
        };
        /**
         * @description One event name's volume over the window.
         * @example {
         *       "name": "signup.started",
         *       "occurrences": 128,
         *       "sessions": 96
         *     }
         */
        EventSummary: {
            name: string;
            occurrences: number;
            /** @description Distinct sessions, which is the number that answers "how many people" rather than "how many times". */
            sessions: number;
        };
        /**
         * @description The window to recompute, half-open. Bucketed by day, which is the only
         *     bucket the panel asks for — an hourly funnel is noise at this platform's
         *     volume, and a weekly one hides the day a release broke a step.
         * @example {
         *       "from": "2026-08-13T00:00:00Z",
         *       "to": "2026-08-20T00:00:00Z"
         *     }
         */
        RollupWindow: {
            /**
             * Format: date-time
             * @description Inclusive start.
             */
            from: string;
            /**
             * Format: date-time
             * @description Exclusive end.
             */
            to: string;
        };
        /**
         * @description What the pass wrote.
         * @example {
         *       "funnel": "checkout",
         *       "buckets": 7,
         *       "rows": 28
         *     }
         */
        RollupResult: {
            funnel: string;
            /** @description Day buckets covered by the window. */
            buckets: number;
            /** @description Rows written */
            rows: number;
        };
        /**
         * @description One funnel step's session count in one bucket.
         * @example {
         *       "funnel": "checkout",
         *       "step_index": 0,
         *       "step_name": "product_viewed",
         *       "bucket_start": "2026-08-19T00:00:00Z",
         *       "bucket_end": "2026-08-20T00:00:00Z",
         *       "sessions": 412
         *     }
         */
        FunnelRollupRow: {
            funnel: string;
            /** @description Zero-based position in the funnel. */
            step_index: number;
            step_name: string;
            /** Format: date-time */
            bucket_start: string;
            /** Format: date-time */
            bucket_end: string;
            /**
             * @description Sessions that reached this step IN ORDER — having reached every earlier
             *     step first. A session that arrives at a later step directly is not
             *     counted, because it did not traverse the funnel.
             */
            sessions: number;
        };
        /** @description A consent decision, as it is recorded for later demonstration (GDPR Art. 7(1)). */
        ConsentInput: {
            session_id: string;
            identity_id?: string;
            /** @enum {string} */
            state: "granted" | "withdrawn" | "refused";
            /** @description The version of the purpose text shown. Consent is to a stated purpose, so a changed purpose is a new consent rather than a continuing one. */
            purpose_version: string;
            /**
             * @description `gpc` is a Global Privacy Control signal — a refusal nobody was prompted for.
             * @enum {string}
             */
            source: "control" | "gpc";
        };
        /**
         * @description A recorded consent decision.
         * @example {
         *       "session_id": "4f3b9c22",
         *       "state": "refused",
         *       "purpose_version": "2026-08-01",
         *       "source": "gpc",
         *       "decided_at": "2026-08-19T10:00:00Z"
         *     }
         */
        Consent: {
            session_id: string;
            identity_id?: string;
            /** @enum {string} */
            state: "granted" | "withdrawn" | "refused";
            purpose_version: string;
            /** @enum {string} */
            source: "control" | "gpc";
            /** Format: date-time */
            decided_at: string;
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recordEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The events to record. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventBatch"];
            };
        };
        responses: {
            /**
             * @description Accepted. The count that was STORED, which is not necessarily the count
             *     that was sent: an event whose session has no recorded consent is dropped
             *     here (ADR-0700's second enforcement point), because the first one runs on
             *     a client this platform does not control.
             */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    summariseEvents: {
        parameters: {
            query: {
                /** @description The start of the window. */
                since: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per event name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getFunnelRollup: {
        parameters: {
            query: {
                /** @description The first bucket to return. */
                from: string;
                /** @description Exclusive end of the range. */
                to: string;
            };
            header?: never;
            path: {
                /** @description The funnel's id. */
                funnel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per bucket and step. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelRollupRow"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    computeFunnelRollup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The funnel's id, from infra/analytics/funnels.yaml. */
                funnel: string;
            };
            cookie?: never;
        };
        /** @description The window to recompute. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollupWindow"];
            };
        };
        responses: {
            /** @description The buckets that were written. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollupResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getConsent: {
        parameters: {
            query: {
                /** @description The session to read. */
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decision on file for that session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    recordConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The consent decision. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentInput"];
            };
        };
        responses: {
            /** @description The decision as recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
