// Code generated by ogen, DO NOT EDIT.

package orgs

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// DeleteOrgNoContent is response for DeleteOrg operation.
type DeleteOrgNoContent struct{}

// The value that replaces the identity in every row. The workflow chooses one per erasure.
// Ref: #/components/schemas/ErasureRequest
type ErasureRequest struct {
	Pseudonym string `json:"pseudonym"`
}

// GetPseudonym returns the value of Pseudonym.
func (s *ErasureRequest) GetPseudonym() string {
	return s.Pseudonym
}

// SetPseudonym sets the value of Pseudonym.
func (s *ErasureRequest) SetPseudonym(val string) {
	s.Pseudonym = val
}

// The rows that the erasure changed.
// Ref: #/components/schemas/ErasureResult
type ErasureResult struct {
	Rows int `json:"rows"`
}

// GetRows returns the value of Rows.
func (s *ErasureResult) GetRows() int {
	return s.Rows
}

// SetRows sets the value of Rows.
func (s *ErasureResult) SetRows(val int) {
	s.Rows = val
}

// ErrorStatusCode wraps Problem with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// OnIdentityCreatedNoContent is response for OnIdentityCreated operation.
type OnIdentityCreatedNoContent struct{}

// Kratos identity-created payload.
type OnIdentityCreatedReq struct {
	IdentityID OptString `json:"identity_id"`
	Email      OptString `json:"email"`
}

// GetIdentityID returns the value of IdentityID.
func (s *OnIdentityCreatedReq) GetIdentityID() OptString {
	return s.IdentityID
}

// GetEmail returns the value of Email.
func (s *OnIdentityCreatedReq) GetEmail() OptString {
	return s.Email
}

// SetIdentityID sets the value of IdentityID.
func (s *OnIdentityCreatedReq) SetIdentityID(val OptString) {
	s.IdentityID = val
}

// SetEmail sets the value of Email.
func (s *OnIdentityCreatedReq) SetEmail(val OptString) {
	s.Email = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// An organization.
// Ref: #/components/schemas/Org
type Org struct {
	ID   OrgId  `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *Org) GetID() OrgId {
	return s.ID
}

// GetName returns the value of Name.
func (s *Org) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Org) SetID(val OrgId) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Org) SetName(val string) {
	s.Name = val
}

type OrgId string

// Request body to create an organization.
// Ref: #/components/schemas/OrgInput
type OrgInput struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *OrgInput) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *OrgInput) SetName(val string) {
	s.Name = val
}

// RFC 9457 problem details. Services and the edge both serve it as `application/problem+json`, so a
// generated client has one error branch, not two.
// Ref: #/components/schemas/Problem
type Problem struct {
	// `about:blank`, except where two errors share a status code and a client handles them differently.
	// That case uses a `urn:problem-type:<service>:<slug>` URN. It is never a dereferenceable URL, which
	// would put an error taxonomy into the flat public URL namespace.
	Type string `json:"type"`
	// A stable, human-readable summary. It does not change with the instance.
	Title string `json:"title"`
	// The HTTP status, repeated in the body.
	Status int `json:"status"`
	// Specific to the instance and safe to show a user. Never a stack trace, a query, or an internal
	// hostname.
	Detail OptString `json:"detail"`
	// The W3C Trace Context trace-id of the failing request, so an error that a user reports leads to its
	// trace. The active span supplies it, not the handler.
	TraceID OptString `json:"trace_id"`
	// Field-level validation failures, filled from the generated validator. Absent when the failure is not
	// a validation failure.
	Errors []ProblemErrorsItem `json:"errors"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetTraceID returns the value of TraceID.
func (s *Problem) GetTraceID() OptString {
	return s.TraceID
}

// GetErrors returns the value of Errors.
func (s *Problem) GetErrors() []ProblemErrorsItem {
	return s.Errors
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetTraceID sets the value of TraceID.
func (s *Problem) SetTraceID(val OptString) {
	s.TraceID = val
}

// SetErrors sets the value of Errors.
func (s *Problem) SetErrors(val []ProblemErrorsItem) {
	s.Errors = val
}

type ProblemErrorsItem struct {
	// RFC 6901 JSON Pointer to the member that failed.
	Pointer string `json:"pointer"`
	Message string `json:"message"`
}

// GetPointer returns the value of Pointer.
func (s *ProblemErrorsItem) GetPointer() string {
	return s.Pointer
}

// GetMessage returns the value of Message.
func (s *ProblemErrorsItem) GetMessage() string {
	return s.Message
}

// SetPointer sets the value of Pointer.
func (s *ProblemErrorsItem) SetPointer(val string) {
	s.Pointer = val
}

// SetMessage sets the value of Message.
func (s *ProblemErrorsItem) SetMessage(val string) {
	s.Message = val
}

// One membership of the subject.
// Ref: #/components/schemas/SubjectMembership
type SubjectMembership struct {
	OrgID   OrgId                 `json:"org_id"`
	OrgName string                `json:"org_name"`
	Role    SubjectMembershipRole `json:"role"`
}

// GetOrgID returns the value of OrgID.
func (s *SubjectMembership) GetOrgID() OrgId {
	return s.OrgID
}

// GetOrgName returns the value of OrgName.
func (s *SubjectMembership) GetOrgName() string {
	return s.OrgName
}

// GetRole returns the value of Role.
func (s *SubjectMembership) GetRole() SubjectMembershipRole {
	return s.Role
}

// SetOrgID sets the value of OrgID.
func (s *SubjectMembership) SetOrgID(val OrgId) {
	s.OrgID = val
}

// SetOrgName sets the value of OrgName.
func (s *SubjectMembership) SetOrgName(val string) {
	s.OrgName = val
}

// SetRole sets the value of Role.
func (s *SubjectMembership) SetRole(val SubjectMembershipRole) {
	s.Role = val
}

type SubjectMembershipRole string

const (
	SubjectMembershipRoleAdmin  SubjectMembershipRole = "admin"
	SubjectMembershipRoleMember SubjectMembershipRole = "member"
)

// AllValues returns all SubjectMembershipRole values.
func (SubjectMembershipRole) AllValues() []SubjectMembershipRole {
	return []SubjectMembershipRole{
		SubjectMembershipRoleAdmin,
		SubjectMembershipRoleMember,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SubjectMembershipRole) MarshalText() ([]byte, error) {
	switch s {
	case SubjectMembershipRoleAdmin:
		return []byte(s), nil
	case SubjectMembershipRoleMember:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SubjectMembershipRole) UnmarshalText(data []byte) error {
	switch SubjectMembershipRole(data) {
	case SubjectMembershipRoleAdmin:
		*s = SubjectMembershipRoleAdmin
		return nil
	case SubjectMembershipRoleMember:
		*s = SubjectMembershipRoleMember
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A subject's memberships.
// Ref: #/components/schemas/SubjectMemberships
type SubjectMemberships struct {
	Memberships []SubjectMembership `json:"memberships"`
}

// GetMemberships returns the value of Memberships.
func (s *SubjectMemberships) GetMemberships() []SubjectMembership {
	return s.Memberships
}

// SetMemberships sets the value of Memberships.
func (s *SubjectMemberships) SetMemberships(val []SubjectMembership) {
	s.Memberships = val
}

// One page of subjects. `next` is absent on the last page.
// Ref: #/components/schemas/SubjectPage
type SubjectPage struct {
	Subjects []string `json:"subjects"`
	// The cursor for the next page.
	Next OptString `json:"next"`
}

// GetSubjects returns the value of Subjects.
func (s *SubjectPage) GetSubjects() []string {
	return s.Subjects
}

// GetNext returns the value of Next.
func (s *SubjectPage) GetNext() OptString {
	return s.Next
}

// SetSubjects sets the value of Subjects.
func (s *SubjectPage) SetSubjects(val []string) {
	s.Subjects = val
}

// SetNext sets the value of Next.
func (s *SubjectPage) SetNext(val OptString) {
	s.Next = val
}
