// Code generated by ogen, DO NOT EDIT.

package orgs

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateOrg implements createOrg operation.
	//
	// Create an organization.
	//
	// POST /orgs
	CreateOrg(ctx context.Context, req *OrgInput) (*Org, error)
	// GetOrg implements getOrg operation.
	//
	// Fetch an organization by id.
	//
	// GET /orgs/{id}
	GetOrg(ctx context.Context, params GetOrgParams) (*Org, error)
	// OnIdentityCreated implements onIdentityCreated operation.
	//
	// Kratos post-registration webhook. Creates a personal org for the new identity.
	//
	// POST /internal/identity-created
	OnIdentityCreated(ctx context.Context, req *OnIdentityCreatedReq) error
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
