// Code generated by ogen, DO NOT EDIT.

package orgs

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateOrgOperation         OperationName = "CreateOrg"
	GetOrgOperation            OperationName = "GetOrg"
	OnIdentityCreatedOperation OperationName = "OnIdentityCreated"
)
