// Code generated by ogen, DO NOT EDIT.

package catalog

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateProductOperation OperationName = "CreateProduct"
	GetProductOperation    OperationName = "GetProduct"
	ListProductsOperation  OperationName = "ListProducts"
)
