// Code generated by ogen, DO NOT EDIT.

package catalog

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateProduct implements createProduct operation.
	//
	// Create a product.
	//
	// POST /products
	CreateProduct(ctx context.Context, req *ProductInput) (*Product, error)
	// DeleteProduct implements deleteProduct operation.
	//
	// Delete a product.
	//
	// DELETE /products/{id}
	DeleteProduct(ctx context.Context, params DeleteProductParams) error
	// GetProduct implements getProduct operation.
	//
	// Fetch a product by id.
	//
	// GET /products/{id}
	GetProduct(ctx context.Context, params GetProductParams) (*Product, error)
	// ListProducts implements listProducts operation.
	//
	// List all products.
	//
	// GET /products
	ListProducts(ctx context.Context) ([]Product, error)
	// UpdateProduct implements updateProduct operation.
	//
	// Update a product.
	//
	// PUT /products/{id}
	UpdateProduct(ctx context.Context, req *ProductInput, params UpdateProductParams) (*Product, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
