/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all organizations. */
        get: operations["listOrgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch an organization by id. */
        get: operations["getOrg"];
        /** @description Rename an organization. */
        put: operations["updateOrg"];
        post?: never;
        /** @description Delete an organization. */
        delete: operations["deleteOrg"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity-created": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Kratos post-registration webhook. Creates a personal org for the new identity. */
        post: operations["onIdentityCreated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject-data/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One page of the identities that hold memberships, in identity order. */
        get: operations["listMemberSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject-data/orgs/{identity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every org that the subject is a member of, with the role. */
        get: operations["exportOrgsSubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject-data/orgs/{identity_id}/erase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Anonymise the subject's memberships. The orgs stay. Safe to run again. */
        post: operations["eraseOrgsSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457 problem details. Services and the edge both serve it as
         *     `application/problem+json`, so a generated client has one error branch, not two.
         * @example {
         *       "type": "about:blank",
         *       "title": "Not Found",
         *       "status": 404,
         *       "detail": "No product with that identifier.",
         *       "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736"
         *     }
         */
        Problem: {
            /**
             * @description `about:blank`, except where two errors share a status code and a client
             *     handles them differently. That case uses a `urn:problem-type:<service>:<slug>`
             *     URN. It is never a dereferenceable URL, which would put an error taxonomy into
             *     the flat public URL namespace.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * @description A stable, human-readable summary. It does not change with the instance.
             * @example Not Found
             */
            title: string;
            /**
             * @description The HTTP status, repeated in the body.
             * @example 404
             */
            status: number;
            /**
             * @description Specific to the instance and safe to show a user. Never a stack trace, a query,
             *     or an internal hostname.
             * @example No product with that identifier.
             */
            detail?: string;
            /**
             * @description The W3C Trace Context trace-id of the failing request, so an error that a user
             *     reports leads to its trace. The active span supplies it, not the handler.
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string;
            /**
             * @description Field-level validation failures, filled from the generated validator.
             *     Absent when the failure is not a validation failure.
             */
            errors?: {
                /**
                 * @description RFC 6901 JSON Pointer to the member that failed.
                 * @example /price/amount
                 */
                pointer: string;
                /** @example must be a decimal amount */
                message: string;
            }[];
        };
        /**
         * @description An organization identifier: `org_` and the UUIDv7 in 26 characters of Crockford
         *     base32. The first character is at most 7, because 26 characters hold 130 bits and
         *     a UUID has 128. It is opaque to a consumer: nothing parses, orders, or builds one.
         * @example org_01kztn9tsrea7b1597q3yjdeav
         */
        OrgId: string;
        /**
         * @description One page of subjects. `next` is absent on the last page.
         * @example {
         *       "subjects": [
         *         "0b6f6f2e-5d3b-4f39-9a5e-3c7a1d1e2f40"
         *       ],
         *       "next": "0b6f6f2e-5d3b-4f39-9a5e-3c7a1d1e2f40"
         *     }
         */
        SubjectPage: {
            subjects: string[];
            /** @description The cursor for the next page. */
            next?: string;
        };
        /** @description The value that replaces the identity in every row. The workflow chooses one per erasure. */
        ErasureRequest: {
            pseudonym: string;
        };
        /**
         * @description The rows that the erasure changed.
         * @example {
         *       "rows": 1
         *     }
         */
        ErasureResult: {
            rows: number;
        };
        /** @description One membership of the subject. */
        SubjectMembership: {
            org_id: components["schemas"]["OrgId"];
            org_name: string;
            /** @enum {string} */
            role: "admin" | "member";
        };
        /**
         * @description A subject's memberships.
         * @example {
         *       "memberships": [
         *         {
         *           "org_id": "org_01kztnj6c8e0jt7vzw0cn1wxvd",
         *           "org_name": "Personal",
         *           "role": "admin"
         *         }
         *       ]
         *     }
         */
        SubjectMemberships: {
            memberships: components["schemas"]["SubjectMembership"][];
        };
        /**
         * @description An organization.
         * @example {
         *       "id": "org_01kztn9tsrea7b1597q3yjdeav",
         *       "name": "Northwind Trading"
         *     }
         */
        Org: {
            id: components["schemas"]["OrgId"];
            name: string;
        };
        /** @description Request body to create an organization. */
        OrgInput: {
            name: string;
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id. */
                id: components["schemas"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the organization to update. */
                id: components["schemas"]["OrgId"];
            };
            cookie?: never;
        };
        /** @description The new organization fields. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgInput"];
            };
        };
        responses: {
            /** @description The updated organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the organization to delete. */
                id: components["schemas"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    onIdentityCreated: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The newly created identity. */
        requestBody: {
            content: {
                "application/json": {
                    identity_id?: string;
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Ack */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listMemberSubjects: {
        parameters: {
            query?: {
                /** @description The last identity of the previous page. */
                after?: string;
                /** @description The page size. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportOrgsSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Kratos identity. */
                identity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subject's memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectMemberships"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    eraseOrgsSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Kratos identity. */
                identity_id: string;
            };
            cookie?: never;
        };
        /** @description The replacement for the identity. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ErasureRequest"];
            };
        };
        responses: {
            /** @description The rows that changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
