// Command adr-rules generates the two documents that are views over the ADR set's Rules
// sections, and drift-checks them in CI like any other generated artefact.
//
//	docs/reference/rules-index.md   every rule in the set, with its enforcement
//	docs/security-baseline.md       the annotated rules of the security-owning ADRs
//
// Both were hand-maintained copies of facts owned elsewhere, which is the drift the
// repository's own principle 9 exists to stop. Generating them makes an ADR's Rules
// section the single source: a rule is edited once, in the ADR that owns it.
//
// Usage:
//
//	adr-rules          write both documents
//	adr-rules -check   fail if either differs from what the ADRs produce
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	adrDir       = "docs/adr"
	rulesPath    = "docs/reference/rules-index.md"
	baselinePath = "docs/security-baseline.md"
	generated    = "<!-- Generated by tools/adr-rules. Edit the owning ADR's Rules section, then run `mise run gen`. -->"
)

// The prose each generated document opens with. Held as constants so the renderers
// read as structure rather than as paragraphs.
const (
	rulesIntro = "Every normative rule in the ADR set, in one place, with the mechanism that enforces it. The" +
		" rule's owning ADR carries the reasoning; this document carries only the rule, so a reviewer can" +
		" read the whole law without reading the whole set.\n\n"
	rulesReview = "An unannotated rule is enforced by review. It is normative on the same terms as an annotated" +
		" one — the annotation states where the gate is, not how binding the rule is" +
		" ([ADR-0001](../adr/0001-documentation-and-output-conventions.md)).\n\n"
	rulesRatio = "The ratio is a fact about the set rather than a target. A rule moves into the first row when a" +
		" check is written for it, and the count moving the wrong way is the signal worth reading.\n"
	baselineIntro = "The security controls every project built from this template inherits, each one a rule from the" +
		" ADR that owns it and the mechanism that enforces it. It is generated from those Rules sections," +
		" so a control cannot be described here and decided differently there.\n\n"
	baselineScope = "**Scope.** Controls that hold for every instance. What a particular project turns on for its" +
		" own risk profile or its own compliance framework is" +
		" [`per-instance-hardening.md`](reference/per-instance-hardening.md), which is written rather" +
		" than generated because it is a property of the project rather than of the template.\n\n"
	baselineReview = "**A control with no annotation is enforced by review.** That is a weaker gate and a normative rule" +
		" either way, and the distinction is visible here for the same reason it is visible in the ADRs.\n"
)

var (
	adrFile    = regexp.MustCompile(`^(\d{4})-[a-z0-9-]+\.md$`)
	titleLine  = regexp.MustCompile(`^# ADR-(\d{4}): (.+)$`)
	annotation = regexp.MustCompile("`\\((CI|enforced|ref): ([^)]*)\\)`")
	// A rule's links are written relative to docs/adr/. Both generated documents sit
	// elsewhere, so the links are rebased rather than reproduced.
	adrLink = regexp.MustCompile(`\]\(((?:\d{4}-[a-z0-9-]+|README|_template)\.md)\)`)
	upLink  = regexp.MustCompile(`\]\(\.\./([^)]+)\)`)
)

// securityAreas names the ADRs whose rules constitute the security baseline, and the
// control area each owns. An ADR outside this map states rules that are not security
// controls; adding one is a deliberate edit here rather than a side effect of writing a
// rule that mentions a credential.
var securityAreas = map[string]string{
	"0104": "Supply chain",
	"0200": "Node and workload isolation",
	"0202": "Secrets",
	"0206": "Network isolation",
	"0207": "Durable data and recovery",
	"0203": "Policy enforcement",
	"0301": "Data lifecycle and privacy",
	"0304": "Identity and authorization",
	"0305": "Edge authentication and traffic policy",
	"0306": "Trust tiers and origins",
	"0307": "Outbound mail",
	"0700": "Analytics and consent",
}

// adr is one decision record, reduced to what these two documents need.
type adr struct {
	num   string
	title string
	file  string
	rules []rule
}

// rule is one normative bullet, with the mechanism that enforces it if any.
type rule struct {
	text  string // the bullet, annotation stripped
	gates []gate // the mechanisms named, in the order written
}

// gate is one enforcement mechanism: a CI task, an admission policy, or a standard.
type gate struct {
	kind string
	via  string
}

func main() {
	check := flag.Bool("check", false, "fail if a generated document is out of date")
	flag.Parse()

	set, err := loadADRs()
	if err != nil {
		failf("%v", err)
	}
	docs := map[string]string{
		rulesPath:    renderRulesIndex(set),
		baselinePath: renderBaseline(set),
	}
	stale := make([]string, 0, len(docs))
	for path, want := range docs {
		if *check {
			got, err := os.ReadFile(path)
			if err != nil || string(got) != want {
				stale = append(stale, path)
			}
			continue
		}
		err := os.MkdirAll(filepath.Dir(path), 0o755)
		if err != nil {
			failf("%v", err)
		}
		err = os.WriteFile(path, []byte(want), 0o600)
		if err != nil {
			failf("%v", err)
		}
	}
	if len(stale) > 0 {
		sort.Strings(stale)
		_, _ = fmt.Fprintln(os.Stderr, "✗ generated rule documents are out of date:")
		for _, p := range stale {
			_, _ = fmt.Fprintln(os.Stderr, "  "+p)
		}
		_, _ = fmt.Fprintln(os.Stderr, "  run: mise run gen:adr-rules")
		os.Exit(1)
	}
	if *check {
		_, _ = fmt.Fprintln(os.Stdout, "✓ generated rule documents match the ADR set")
		return
	}
	_, _ = fmt.Fprintf(os.Stdout, "✓ wrote %s and %s\n", rulesPath, baselinePath)
}

func loadADRs() ([]adr, error) {
	entries, err := os.ReadDir(adrDir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", adrDir, err)
	}
	var set []adr
	for _, e := range entries {
		m := adrFile.FindStringSubmatch(e.Name())
		if m == nil {
			continue
		}
		body, err := os.ReadFile(filepath.Join(adrDir, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", e.Name(), err)
		}
		a := adr{num: m[1], file: e.Name()}
		inRules := false
		for line := range strings.SplitSeq(string(body), "\n") {
			t := titleLine.FindStringSubmatch(line)
			if t != nil {
				a.title = t[2]
			}
			if strings.HasPrefix(line, "## ") {
				inRules = line == "## Rules"
				continue
			}
			if !inRules || !strings.HasPrefix(line, "- ") {
				continue
			}
			a.rules = append(a.rules, parseRule(strings.TrimPrefix(line, "- ")))
		}
		set = append(set, a)
	}
	sort.Slice(set, func(i, j int) bool { return set[i].num < set[j].num })
	return set, nil
}

// parseRule splits a bullet into its statement and its gates. A rule may name more
// than one — digest pinning is linted in CI and enforced at admission — and the two are
// different subjects rather than a repetition, so both are kept.
func parseRule(text string) rule {
	r := rule{text: text}
	m := annotation.FindStringSubmatch(text)
	if m == nil {
		return r
	}
	r.text = strings.TrimSpace(annotation.ReplaceAllString(text, ""))
	kind := m[1]
	for part := range strings.SplitSeq(m[1]+": "+m[2], ";") {
		part = strings.TrimSpace(part)
		k, via, ok := strings.Cut(part, ": ")
		if ok && (k == "CI" || k == "enforced" || k == "ref") {
			kind = k
			r.gates = append(r.gates, gate{kind: k, via: strings.TrimSpace(via)})
			continue
		}
		r.gates = append(r.gates, gate{kind: kind, via: part})
	}
	return r
}

// rebase rewrites a rule's links for the document it is being written into. Rules are
// authored inside docs/adr/, so a bare ADR filename and a ../ escape both need a prefix.
func rebase(s, adrPrefix, upPrefix string) string {
	s = adrLink.ReplaceAllString(s, "]("+adrPrefix+"$1)")
	return upLink.ReplaceAllString(s, "]("+upPrefix+"$1)")
}

func renderRulesIndex(set []adr) string {
	var b strings.Builder
	total, annotated := 0, 0
	for _, a := range set {
		for _, r := range a.rules {
			total++
			if len(r.gates) > 0 {
				annotated++
			}
		}
	}
	w(&b, "# Rules Index\n\n")
	w(&b, generated+"\n\n")
	w(&b, rulesIntro)
	w(&b, rulesReview)
	w(&b, "| Enforcement | Rules |\n| --- | --- |\n")
	w(&b, fmt.Sprintf("| Machine-enforced | %d |\n", annotated))
	w(&b, fmt.Sprintf("| Review-enforced | %d |\n", total-annotated))
	w(&b, fmt.Sprintf("| **Total** | **%d** |\n\n", total))
	w(&b, rulesRatio)

	for _, a := range set {
		if len(a.rules) == 0 {
			continue
		}
		w(&b, fmt.Sprintf("\n## ADR-%s — %s\n\n", a.num, a.title))
		w(&b, fmt.Sprintf("[Full decision](../adr/%s)\n\n", a.file))
		w(&b, "| Rule | Enforced by |\n| --- | --- |\n")
		for _, r := range a.rules {
			w(&b, fmt.Sprintf("| %s | %s |\n", cell(rebase(r.text, "../adr/", "../")), enforcement(r)))
		}
	}
	return b.String()
}

func renderBaseline(set []adr) string {
	var b strings.Builder
	w(&b, "# Security Baseline\n\n")
	w(&b, generated+"\n\n")
	w(&b, baselineIntro)
	w(&b, baselineScope)
	w(&b, baselineReview)

	areas := make([]string, 0, len(securityAreas))
	for num := range securityAreas {
		areas = append(areas, num)
	}
	sort.Strings(areas)
	for _, num := range areas {
		for _, a := range set {
			if a.num != num || len(a.rules) == 0 {
				continue
			}
			w(&b, fmt.Sprintf("\n## %s\n\n", securityAreas[num]))
			w(&b, fmt.Sprintf("[ADR-%s — %s](adr/%s)\n\n", a.num, a.title, a.file))
			w(&b, "| Control | Enforced by |\n| --- | --- |\n")
			for _, r := range a.rules {
				w(&b, fmt.Sprintf("| %s | %s |\n", cell(rebase(r.text, "adr/", "")), enforcement(r)))
			}
		}
	}
	return b.String()
}

// enforcement renders the mechanism cell. The three annotation kinds mean different
// things: a task runs, a policy admits, a standard is adopted.
func enforcement(r rule) string {
	if len(r.gates) == 0 {
		return "review"
	}
	parts := make([]string, 0, len(r.gates))
	for _, g := range r.gates {
		switch g.kind {
		case "CI":
			parts = append(parts, "`"+g.via+"` in CI")
		case "enforced":
			parts = append(parts, "admission: "+g.via)
		case "ref":
			parts = append(parts, "standard: "+g.via)
		}
	}
	return strings.Join(parts, "; ")
}

// cell makes a rule safe inside a table: a pipe in a rule would end the column.
func cell(s string) string {
	return strings.ReplaceAll(strings.TrimSpace(s), "|", `\|`)
}

// w appends to the document under construction. A strings.Builder never returns a
// non-nil error, so the discard is total rather than a shortcut.
func w(b *strings.Builder, s string) {
	_, _ = b.WriteString(s)
}

func failf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "✗ "+format+"\n", args...)
	os.Exit(1)
}
