// Code generated by ogen, DO NOT EDIT.

package orders

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Checkout implements checkout operation.
	//
	// Starts the Checkout Temporal saga (ADR-0006).
	//
	// POST /orders
	Checkout(ctx context.Context, req *CheckoutInput) (*WorkflowHandle, error)
	// GetOrder implements getOrder operation.
	//
	// Fetch an order by id.
	//
	// GET /orders/{id}
	GetOrder(ctx context.Context, params GetOrderParams) (*Order, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
