// Code generated by ogen, DO NOT EDIT.

package orders

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Checkout implements checkout operation.
//
// Starts the Checkout Temporal saga (ADR-0006).
//
// POST /orders
func (UnimplementedHandler) Checkout(ctx context.Context, req *CheckoutInput) (r *WorkflowHandle, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements getOrder operation.
//
// Fetch an order by id.
//
// GET /orders/{id}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r *Order, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
