// Code generated by ogen, DO NOT EDIT.

package orders

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements cancelOrder operation.
	//
	// Cancel an order. Starts the CancelOrder workflow, per ADR-0302.
	//
	// POST /orders/{id}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (*WorkflowHandle, error)
	// Checkout implements checkout operation.
	//
	// Starts the Checkout Temporal saga, per ADR-0302. It is idempotent on the Idempotency-Key header: a
	// retry of the same request returns the order that the first one created and does not place a second
	// order.
	//
	// POST /orders
	Checkout(ctx context.Context, req *CheckoutInput, params CheckoutParams) (*WorkflowHandle, error)
	// EraseOrdersSubject implements eraseOrdersSubject operation.
	//
	// Anonymise the owner of the subject's orders. The orders stay, because they carry a bookkeeping
	// obligation. Safe to run again.
	//
	// POST /subject-data/orders/{identity_id}/erase
	EraseOrdersSubject(ctx context.Context, req *ErasureRequest, params EraseOrdersSubjectParams) (*ErasureResult, error)
	// ExportOrdersSubject implements exportOrdersSubject operation.
	//
	// Every order that the subject placed.
	//
	// GET /subject-data/orders/{identity_id}
	ExportOrdersSubject(ctx context.Context, params ExportOrdersSubjectParams) (*SubjectOrders, error)
	// GetOrder implements getOrder operation.
	//
	// Fetch an order by id.
	//
	// GET /orders/{id}
	GetOrder(ctx context.Context, params GetOrderParams) (*Order, error)
	// ListOrderSubjects implements listOrderSubjects operation.
	//
	// One page of the identities that own orders, in identity order.
	//
	// GET /subject-data/orders
	ListOrderSubjects(ctx context.Context, params ListOrderSubjectsParams) (*SubjectPage, error)
	// ListOrders implements listOrders operation.
	//
	// List all orders.
	//
	// GET /orders
	ListOrders(ctx context.Context) ([]Order, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
