// GENERATED by `mise run gen:zod` — do not edit.
//
// Zod schemas for the request bodies in analytics/openapi.yaml (ADR-0400). Forms
// validate with these through the shared <Form> primitive, so the rule a field
// enforces in the browser is the rule the spec states.
import { z } from "zod";

export const consentInputSchema = z.object({
  identity_id: z.string().optional(),
  purpose_version: z.string().min(1),
  session_id: z.string().min(1),
  source: z.enum(["control", "gpc"]),
  state: z.enum(["granted", "withdrawn", "refused"]),
});

export const eventSchema = z.object({
  name: z.string().min(1),
  occurred_at: z.string().datetime(),
  properties: z.object({}).optional(),
});

export const eventBatchSchema = z.object({
  device_class: z.enum(["mobile", "tablet", "desktop", "unknown"]).optional(),
  events: z.array(eventSchema),
  identity_id: z.string().optional(),
  session_id: z.string().min(1),
});

export const rollupWindowSchema = z.object({
  from: z.string().datetime(),
  to: z.string().datetime(),
});

export const computeFunnelRollupSchema = rollupWindowSchema;
export type ComputeFunnelRollupInput = z.infer<typeof computeFunnelRollupSchema>;

export const recordConsentSchema = consentInputSchema;
export type RecordConsentInput = z.infer<typeof recordConsentSchema>;

export const recordEventsSchema = eventBatchSchema;
export type RecordEventsInput = z.infer<typeof recordEventsSchema>;
