// GENERATED by `mise run gen:zod`. Do not edit.
//
// Zod schemas for the request bodies in authz/openapi.yaml, per ADR-0400. Forms
// validate with these through the shared <Form> primitive, so a field in the
// browser enforces the same rule that the spec states.
import { z } from "zod";

export const authorizeRequestSchema = z.object({
  aal: z.string(),
  operator: z.string(),
  subject: z.string(),
  tool: z.string(),
});

export const identityUpdateSchema = z.object({
  name: z.string().optional(),
  operator: z.boolean().optional(),
});

export const relationCheckSchema = z.object({
  object: z.string().min(1),
  relation: z.string().min(1),
  subject: z.string().min(1),
});

export const authorizeSchema = authorizeRequestSchema;
export type AuthorizeInput = z.infer<typeof authorizeSchema>;

export const checkRelationSchema = relationCheckSchema;
export type CheckRelationInput = z.infer<typeof checkRelationSchema>;

export const updateIdentitySchema = identityUpdateSchema;
export type UpdateIdentityInput = z.infer<typeof updateIdentitySchema>;
