// GENERATED by `mise run gen:zod`. Do not edit.
//
// Zod schemas for the request bodies in orders/openapi.yaml, per ADR-0400. Forms
// validate with these through the shared <Form> primitive, so a field in the
// browser enforces the same rule that the spec states.
import { z } from "zod";

export const productIdSchema = z.string().regex(/^product_[0-7][0-9abcdefghjkmnpqrstvwxyz]{25}$/);

export const checkoutInputSchema = z.object({
  product_id: productIdSchema,
  quantity: z.number().int().min(1),
});

export const checkoutSchema = checkoutInputSchema;
export type CheckoutInput = z.infer<typeof checkoutSchema>;
