// GENERATED by `mise run gen:zod` — do not edit.
//
// Zod schemas for the request bodies in orgs/openapi.yaml (ADR-0400). Forms
// validate with these through the shared <Form> primitive, so the rule a field
// enforces in the browser is the rule the spec states.
import { z } from "zod";

export const orgInputSchema = z.object({
  name: z.string().min(1),
});

export const onIdentityCreatedSchema = z.object({
  email: z.string().optional(),
  identity_id: z.string().optional(),
});
export type OnIdentityCreatedInput = z.infer<typeof onIdentityCreatedSchema>;

export const updateOrgSchema = orgInputSchema;
export type UpdateOrgInput = z.infer<typeof updateOrgSchema>;
