// GENERATED by `mise run gen:zod`. Do not edit.
//
// Zod schemas for the request bodies in payment/openapi.yaml, per ADR-0400. Forms
// validate with these through the shared <Form> primitive, so a field in the
// browser enforces the same rule that the spec states.
import { z } from "zod";

export const moneySchema = z.object({
  amount: z.string().regex(/^-?[0-9]+(\.[0-9]+)?$/),
  currency: z.string().regex(/^[A-Z]{3}$/),
});

export const orderIdSchema = z.string().regex(/^order_[0-7][0-9abcdefghjkmnpqrstvwxyz]{25}$/);

export const chargeInputSchema = z.object({
  amount: moneySchema,
  order_id: orderIdSchema,
});

export const refundInputSchema = z.object({
  reason: z.string().min(1),
});

export const createChargeSchema = chargeInputSchema;
export type CreateChargeInput = z.infer<typeof createChargeSchema>;

export const refundChargeSchema = refundInputSchema;
export type RefundChargeInput = z.infer<typeof refundChargeSchema>;
