// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"
)

const createItem = `-- name: CreateItem :one
insert into items (name) values ($1) returning id, name, created_at
`

func (q *Queries) CreateItem(ctx context.Context, name string) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, name)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listItems = `-- name: ListItems :many
select
  id,
  name,
  created_at
from items
order by created_at desc limit 100
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
