// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charges.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharge = `-- name: CreateCharge :one
insert into charges (order_id, amount_cents, status, idempotency_key)
values ($1, $2, 'pending', $3)
returning id, order_id, amount_cents, status
`

type CreateChargeParams struct {
	OrderID        pgtype.UUID `json:"order_id"`
	AmountCents    int32       `json:"amount_cents"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type CreateChargeRow struct {
	ID          pgtype.UUID `json:"id"`
	OrderID     pgtype.UUID `json:"order_id"`
	AmountCents int32       `json:"amount_cents"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateCharge(ctx context.Context, arg CreateChargeParams) (CreateChargeRow, error) {
	row := q.db.QueryRow(ctx, createCharge, arg.OrderID, arg.AmountCents, arg.IdempotencyKey)
	var i CreateChargeRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Status,
	)
	return i, err
}

const getByIdempotencyKey = `-- name: GetByIdempotencyKey :one
select
  id,
  order_id,
  amount_cents,
  status
from charges
where idempotency_key = $1
`

type GetByIdempotencyKeyRow struct {
	ID          pgtype.UUID `json:"id"`
	OrderID     pgtype.UUID `json:"order_id"`
	AmountCents int32       `json:"amount_cents"`
	Status      string      `json:"status"`
}

func (q *Queries) GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getByIdempotencyKey, idempotencyKey)
	var i GetByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Status,
	)
	return i, err
}

const getCharge = `-- name: GetCharge :one
select
  id,
  order_id,
  amount_cents,
  status
from charges
where id = $1
`

type GetChargeRow struct {
	ID          pgtype.UUID `json:"id"`
	OrderID     pgtype.UUID `json:"order_id"`
	AmountCents int32       `json:"amount_cents"`
	Status      string      `json:"status"`
}

func (q *Queries) GetCharge(ctx context.Context, id pgtype.UUID) (GetChargeRow, error) {
	row := q.db.QueryRow(ctx, getCharge, id)
	var i GetChargeRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountCents,
		&i.Status,
	)
	return i, err
}

const listCharges = `-- name: ListCharges :many
select
  id,
  order_id,
  amount_cents,
  status
from charges
order by created_at desc limit 100
`

type ListChargesRow struct {
	ID          pgtype.UUID `json:"id"`
	OrderID     pgtype.UUID `json:"order_id"`
	AmountCents int32       `json:"amount_cents"`
	Status      string      `json:"status"`
}

func (q *Queries) ListCharges(ctx context.Context) ([]ListChargesRow, error) {
	rows, err := q.db.Query(ctx, listCharges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChargesRow
	for rows.Next() {
		var i ListChargesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AmountCents,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChargeStatus = `-- name: UpdateChargeStatus :exec
update charges set status = $2
where id = $1
`

type UpdateChargeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateChargeStatus(ctx context.Context, arg UpdateChargeStatusParams) error {
	_, err := q.db.Exec(ctx, updateChargeStatus, arg.ID, arg.Status)
	return err
}
