// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCharge(ctx context.Context, arg CreateChargeParams) (CreateChargeRow, error)
	GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetByIdempotencyKeyRow, error)
	GetCharge(ctx context.Context, id pgtype.UUID) (GetChargeRow, error)
	UpdateChargeStatus(ctx context.Context, arg UpdateChargeStatusParams) error
}

var _ Querier = (*Queries)(nil)
