// Command zod-gen emits a zod schema per request body in every service spec
// (ADR-0400).
//
// ADR-0400 puts form validation on react-hook-form plus zod, and requires the
// schemas for spec operations to be GENERATED and committed. The reason is the
// one every generated artefact here has: a hand-written schema is a second copy
// of the contract, and the copy is what drifts. A form that accepts a field the
// API rejects is a bug the compiler cannot see, because the two descriptions of
// the same body never meet.
//
// # Scope
//
// Request bodies only. Response types already come from openapi-typescript as
// TypeScript types, which is the right tool for a shape you read; a zod schema is
// for a shape you must VALIDATE, and the only such shape in a browser is what a
// form is about to send.
//
// # The subset
//
// This walks the JSON Schema the specs actually use, and fails on anything else
// rather than emitting a schema that silently validates less than the spec says.
// A generator that quietly degrades `pattern` into `z.string()` produces a form
// that accepts what the API refuses — the exact failure it exists to prevent.
package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	outDir = "libs/ts/schemas"
	header = `// GENERATED by ` + "`mise run gen:zod`" + ` — do not edit.
//
// Zod schemas for the request bodies in %s/openapi.yaml (ADR-0400). Forms
// validate with these through the shared <Form> primitive, so the rule a field
// enforces in the browser is the rule the spec states.
import { z } from "zod";
`
)

type schema struct {
	Ref         string             `yaml:"$ref"`
	Type        string             `yaml:"type"`
	Description string             `yaml:"description"`
	Required    []string           `yaml:"required"`
	Properties  map[string]*schema `yaml:"properties"`
	Items       *schema            `yaml:"items"`
	Enum        []string           `yaml:"enum"`
	Format      string             `yaml:"format"`
	Pattern     string             `yaml:"pattern"`
	MinLength   *int               `yaml:"minLength"`
	MaxLength   *int               `yaml:"maxLength"`
	Minimum     *float64           `yaml:"minimum"`
	Maximum     *float64           `yaml:"maximum"`
}

type operation struct {
	OperationID string `yaml:"operationId"`
	RequestBody *struct {
		Content map[string]struct {
			Schema *schema `yaml:"schema"`
		} `yaml:"content"`
	} `yaml:"requestBody"`
}

type spec struct {
	Paths      map[string]map[string]*operation `yaml:"paths"`
	Components struct {
		Schemas map[string]*schema `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	specs, err := filepath.Glob("services/*/openapi.yaml")
	if err != nil {
		failf("glob: %v", err)
	}
	sort.Strings(specs)

	written := 0
	for _, path := range specs {
		service := filepath.Base(filepath.Dir(path))
		if service == "_template" {
			continue
		}
		out, err := render(service, path)
		if err != nil {
			failf("%s: %v", path, err)
		}
		if out == "" {
			continue
		}
		dest := filepath.Join(outDir, service+".ts")
		err = os.MkdirAll(outDir, 0o755)
		if err != nil {
			failf("mkdir: %v", err)
		}
		err = os.WriteFile(dest, []byte(out), 0o600)
		if err != nil {
			failf("write %s: %v", dest, err)
		}
		written++
	}
	_, _ = fmt.Fprintf(os.Stdout, "✓ zod schemas for %d services in %s\n", written, outDir)
}

// render builds one module per service: every request body it declares, plus the
// component schemas those bodies reach through `$ref`.
func render(service, path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read spec: %w", err)
	}
	var s spec
	err = yaml.Unmarshal(raw, &s)
	if err != nil {
		return "", fmt.Errorf("parse spec: %w", err)
	}

	// Emit in operationId order so the file is stable across runs. A generated
	// artefact whose order depends on map iteration is a diff on every run, which
	// trains everyone to ignore its diffs.
	type body struct {
		op  string
		sch *schema
	}
	var bodies []body
	for _, ops := range s.Paths {
		for _, op := range ops {
			if op == nil || op.RequestBody == nil {
				continue
			}
			content, ok := op.RequestBody.Content["application/json"]
			if !ok || content.Schema == nil {
				continue
			}
			bodies = append(bodies, body{op: op.OperationID, sch: content.Schema})
		}
	}
	if len(bodies) == 0 {
		return "", nil
	}
	sort.Slice(bodies, func(i, j int) bool { return bodies[i].op < bodies[j].op })

	var b strings.Builder
	_, _ = fmt.Fprintf(&b, header, service)

	// Component schemas first, and only the ones actually reached: a module that
	// exports every component in the spec exports shapes no form validates.
	needed := map[string]bool{}
	for _, bd := range bodies {
		collect(bd.sch, s.Components.Schemas, needed)
	}
	// DEPENDENCY order, not alphabetical. A zod schema is a `const`, and a `const`
	// is not hoisted: emitting `checkoutInputSchema` before the `productIdSchema`
	// it references produces a module that throws a ReferenceError the moment it is
	// imported. Alphabetical order happened to be right for four of the five
	// services and wrong for the fifth, which is exactly how this kind of bug ships.
	names := dependencyOrder(needed, s.Components.Schemas)
	for _, name := range names {
		expr, err := zodOf(s.Components.Schemas[name], s.Components.Schemas, map[string]bool{name: true}, 0)
		if err != nil {
			return "", fmt.Errorf("component %s: %w", name, err)
		}
		_, _ = fmt.Fprintf(&b, "\nexport const %s = %s;\n", constName(name), expr)
	}

	for _, bd := range bodies {
		expr, err := zodOf(bd.sch, s.Components.Schemas, map[string]bool{}, 0)
		if err != nil {
			return "", fmt.Errorf("operation %s: %w", bd.op, err)
		}
		_, _ = fmt.Fprintf(&b, "\nexport const %sSchema = %s;\n", bd.op, expr)
		_, _ = fmt.Fprintf(&b, "export type %sInput = z.infer<typeof %sSchema>;\n", upperFirst(bd.op), bd.op)
	}
	return b.String(), nil
}

// dependencyOrder returns the needed component names with every schema after the
// schemas it references. Ties break alphabetically so the output is stable.
func dependencyOrder(needed map[string]bool, components map[string]*schema) []string {
	pending := make([]string, 0, len(needed))
	for name := range needed {
		pending = append(pending, name)
	}
	sort.Strings(pending)

	emitted := map[string]bool{}
	var order []string
	var visit func(string)
	visit = func(name string) {
		if emitted[name] {
			return
		}
		// Marked before descending, so a schema that references itself is emitted
		// once rather than recursed into forever. Nothing in these specs is
		// recursive today; a generator that hangs on the first one that is would be
		// a worse failure than the one it prevents.
		emitted[name] = true
		deps := map[string]bool{}
		collect(components[name], components, deps)
		depNames := make([]string, 0, len(deps))
		for dep := range deps {
			depNames = append(depNames, dep)
		}
		sort.Strings(depNames)
		for _, dep := range depNames {
			if dep != name {
				visit(dep)
			}
		}
		order = append(order, name)
	}
	for _, name := range pending {
		visit(name)
	}
	return order
}

// collect records which component schemas a body reaches, transitively.
func collect(s *schema, components map[string]*schema, out map[string]bool) {
	if s == nil {
		return
	}
	if s.Ref != "" {
		name := refName(s.Ref)
		if name == "" || out[name] {
			return
		}
		out[name] = true
		collect(components[name], components, out)
		return
	}
	for _, p := range s.Properties {
		collect(p, components, out)
	}
	collect(s.Items, components, out)
}

// zodOf turns one JSON Schema node into a zod expression.
//
// It refuses what it does not understand. Every unsupported construct here would
// otherwise become a weaker schema than the spec — `z.any()` in place of a
// constraint — and a form that validates less than the API is the defect this
// generator exists to remove.
func zodOf(s *schema, components map[string]*schema, seen map[string]bool, depth int) (string, error) {
	if s == nil {
		return "", errors.New("nil schema")
	}
	if s.Ref != "" {
		name := refName(s.Ref)
		if name == "" {
			return "", fmt.Errorf("unsupported $ref %q: only #/components/schemas/<name> is understood", s.Ref)
		}
		_, ok := components[name]
		if !ok {
			return "", fmt.Errorf("$ref %q resolves to nothing", s.Ref)
		}
		return constName(name), nil
	}

	switch s.Type {
	case "object":
		return zodObject(s, components, seen, depth)
	case "array":
		inner, err := zodOf(s.Items, components, seen, depth)
		if err != nil {
			return "", err
		}
		return "z.array(" + inner + ")", nil
	case "string":
		return zodString(s), nil
	case "integer":
		return zodNumber(s, ".int()"), nil
	case "number":
		return zodNumber(s, ""), nil
	case "boolean":
		return "z.boolean()", nil
	case "":
		return "", errors.New("schema has no `type` and no `$ref`")
	default:
		return "", fmt.Errorf("unsupported type %q", s.Type)
	}
}

func zodObject(s *schema, components map[string]*schema, seen map[string]bool, depth int) (string, error) {
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	keys := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	pad := strings.Repeat("  ", depth+1)
	var b strings.Builder
	_, _ = b.WriteString("z.object({\n")
	for _, k := range keys {
		expr, err := zodOf(s.Properties[k], components, seen, depth+1)
		if err != nil {
			return "", fmt.Errorf("property %s: %w", k, err)
		}
		if !required[k] {
			// `.optional()`, not `.nullish()`: the spec says the member may be
			// absent, which is a different statement from saying it may be null.
			expr += ".optional()"
		}
		_, _ = fmt.Fprintf(&b, "%s%s: %s,\n", pad, quoteKey(k), expr)
	}
	_, _ = fmt.Fprintf(&b, "%s})", strings.Repeat("  ", depth))
	return b.String(), nil
}

func zodString(s *schema) string {
	if len(s.Enum) > 0 {
		quoted := make([]string, 0, len(s.Enum))
		for _, v := range s.Enum {
			quoted = append(quoted, `"`+v+`"`)
		}
		return "z.enum([" + strings.Join(quoted, ", ") + "])"
	}
	out := "z.string()"
	switch s.Format {
	case "date-time":
		out += ".datetime()"
	case "uri", "uri-reference":
		// Deliberately not `.url()`: a uri-reference may be a path on this origin,
		// which `.url()` rejects.
		out += ""
	}
	if s.MinLength != nil {
		out += fmt.Sprintf(".min(%d)", *s.MinLength)
	}
	if s.MaxLength != nil {
		out += fmt.Sprintf(".max(%d)", *s.MaxLength)
	}
	if s.Pattern != "" {
		// The spec's pattern verbatim, as a JS regex. Anchors included: an
		// unanchored JS regex matches a substring, so dropping them would accept
		// every string that merely CONTAINS a valid value.
		out += fmt.Sprintf(".regex(/%s/)", s.Pattern)
	}
	return out
}

func zodNumber(s *schema, suffix string) string {
	out := "z.number()" + suffix
	if s.Minimum != nil {
		out += fmt.Sprintf(".min(%s)", trimFloat(*s.Minimum))
	}
	if s.Maximum != nil {
		out += fmt.Sprintf(".max(%s)", trimFloat(*s.Maximum))
	}
	return out
}

func refName(ref string) string {
	const prefix = "#/components/schemas/"
	if !strings.HasPrefix(ref, prefix) {
		return ""
	}
	return strings.TrimPrefix(ref, prefix)
}

// constName is the exported name for a component schema: `Money` becomes
// `moneySchema`, which reads as a value rather than as the type of the same name
// that openapi-typescript already exports.
func constName(name string) string {
	return lowerFirst(name) + "Schema"
}

// quoteKey quotes a property name only when it is not a bare JS identifier, so
// the common case reads as an object literal rather than as a map.
func quoteKey(k string) string {
	for i, r := range k {
		isAlpha := r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
		isDigit := r >= '0' && r <= '9'
		if isAlpha || (i > 0 && isDigit) {
			continue
		}
		return `"` + k + `"`
	}
	return k
}

func trimFloat(f float64) string {
	s := fmt.Sprintf("%g", f)
	return s
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func failf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "✗ "+format+"\n", args...)
	os.Exit(1)
}
