// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	PriceCents int32              `json:"price_cents"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
