// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
insert into products (name, price_cents) values ($1, $2) returning id, name, price_cents
`

type CreateProductParams struct {
	Name       string `json:"name"`
	PriceCents int32  `json:"price_cents"`
}

type CreateProductRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	PriceCents int32       `json:"price_cents"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceCents)
	var i CreateProductRow
	err := row.Scan(&i.ID, &i.Name, &i.PriceCents)
	return i, err
}

const getProduct = `-- name: GetProduct :one
select
  id,
  name,
  price_cents
from products
where id = $1
`

type GetProductRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	PriceCents int32       `json:"price_cents"`
}

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(&i.ID, &i.Name, &i.PriceCents)
	return i, err
}

const listProducts = `-- name: ListProducts :many
select
  id,
  name,
  price_cents
from products
order by created_at desc limit 100
`

type ListProductsRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	PriceCents int32       `json:"price_cents"`
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PriceCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
