// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The write still fills price_cents alongside price: the column is not dropped yet
	// (see the migration), it is NOT NULL, and a row inserted without it would fail.
	// The follow-up migration that drops it removes this too.
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error)
	ListProducts(ctx context.Context) ([]ListProductsRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
}

var _ Querier = (*Queries)(nil)
