// Code generated by ogen, DO NOT EDIT.

package authz

import (
	"fmt"

	"github.com/go-faster/jx"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// AuthorizeOK is response for Authorize operation.
type AuthorizeOK struct{}

func (*AuthorizeOK) authorizeRes() {}

// The remote_json payload Oathkeeper POSTs per ops-dashboard request.
// Ref: #/components/schemas/AuthorizeRequest
type AuthorizeRequest struct {
	// Kratos identity id; empty for anonymous.
	Subject string `json:"subject"`
	// Ops dashboard slug such as grafana or hubble.
	Tool string `json:"tool"`
	// Authenticator_assurance_level from the session.
	Aal string `json:"aal"`
	// The operator identity trait; "true" when set.
	Operator string `json:"operator"`
}

// GetSubject returns the value of Subject.
func (s *AuthorizeRequest) GetSubject() string {
	return s.Subject
}

// GetTool returns the value of Tool.
func (s *AuthorizeRequest) GetTool() string {
	return s.Tool
}

// GetAal returns the value of Aal.
func (s *AuthorizeRequest) GetAal() string {
	return s.Aal
}

// GetOperator returns the value of Operator.
func (s *AuthorizeRequest) GetOperator() string {
	return s.Operator
}

// SetSubject sets the value of Subject.
func (s *AuthorizeRequest) SetSubject(val string) {
	s.Subject = val
}

// SetTool sets the value of Tool.
func (s *AuthorizeRequest) SetTool(val string) {
	s.Tool = val
}

// SetAal sets the value of Aal.
func (s *AuthorizeRequest) SetAal(val string) {
	s.Aal = val
}

// SetOperator sets the value of Operator.
func (s *AuthorizeRequest) SetOperator(val string) {
	s.Operator = val
}

// ErrorStatusCode wraps Problem with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// A Kratos identity, flattened from its traits for the admin changelist.
// Ref: #/components/schemas/Identity
type Identity struct {
	ID       string    `json:"id"`
	Email    string    `json:"email"`
	Name     OptString `json:"name"`
	Operator OptBool   `json:"operator"`
}

// GetID returns the value of ID.
func (s *Identity) GetID() string {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *Identity) GetEmail() string {
	return s.Email
}

// GetName returns the value of Name.
func (s *Identity) GetName() OptString {
	return s.Name
}

// GetOperator returns the value of Operator.
func (s *Identity) GetOperator() OptBool {
	return s.Operator
}

// SetID sets the value of ID.
func (s *Identity) SetID(val string) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *Identity) SetEmail(val string) {
	s.Email = val
}

// SetName sets the value of Name.
func (s *Identity) SetName(val OptString) {
	s.Name = val
}

// SetOperator sets the value of Operator.
func (s *Identity) SetOperator(val OptBool) {
	s.Operator = val
}

// The editable traits of an identity. Email is the login identifier and is not editable here.
// Ref: #/components/schemas/IdentityUpdate
type IdentityUpdate struct {
	Name     OptString `json:"name"`
	Operator OptBool   `json:"operator"`
}

// GetName returns the value of Name.
func (s *IdentityUpdate) GetName() OptString {
	return s.Name
}

// GetOperator returns the value of Operator.
func (s *IdentityUpdate) GetOperator() OptBool {
	return s.Operator
}

// SetName sets the value of Name.
func (s *IdentityUpdate) SetName(val OptString) {
	s.Name = val
}

// SetOperator sets the value of Operator.
func (s *IdentityUpdate) SetOperator(val OptBool) {
	s.Operator = val
}

// A created operator.
// Ref: #/components/schemas/Operator
type Operator struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

// GetID returns the value of ID.
func (s *Operator) GetID() string {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *Operator) GetEmail() string {
	return s.Email
}

// SetID sets the value of ID.
func (s *Operator) SetID(val string) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *Operator) SetEmail(val string) {
	s.Email = val
}

// Request body to create an operator.
// Ref: #/components/schemas/OperatorInput
type OperatorInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *OperatorInput) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *OperatorInput) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *OperatorInput) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *OperatorInput) SetPassword(val string) {
	s.Password = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProblemDetails returns new OptProblemDetails with value set to v.
func NewOptProblemDetails(v ProblemDetails) OptProblemDetails {
	return OptProblemDetails{
		Value: v,
		Set:   true,
	}
}

// OptProblemDetails is optional ProblemDetails.
type OptProblemDetails struct {
	Value ProblemDetails
	Set   bool
}

// IsSet returns true if OptProblemDetails was set.
func (o OptProblemDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProblemDetails) Reset() {
	var v ProblemDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProblemDetails) SetTo(v ProblemDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProblemDetails) Get() (v ProblemDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProblemDetails) Or(d ProblemDetails) ProblemDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// RFC 7807 problem document.
// Ref: #/components/schemas/Problem
type Problem struct {
	Code    string            `json:"code"`
	Message string            `json:"message"`
	Details OptProblemDetails `json:"details"`
}

// GetCode returns the value of Code.
func (s *Problem) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Problem) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Problem) GetDetails() OptProblemDetails {
	return s.Details
}

// SetCode sets the value of Code.
func (s *Problem) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Problem) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Problem) SetDetails(val OptProblemDetails) {
	s.Details = val
}

func (*Problem) authorizeRes() {}

type ProblemDetails map[string]jx.Raw

func (s *ProblemDetails) init() ProblemDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}
