// Code generated by ogen, DO NOT EDIT.

package authz

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthorizeOperation      OperationName = "Authorize"
	CreateOperatorOperation OperationName = "CreateOperator"
	GetIdentityOperation    OperationName = "GetIdentity"
	ListIdentitiesOperation OperationName = "ListIdentities"
	UpdateIdentityOperation OperationName = "UpdateIdentity"
)
