// Code generated by ogen, DO NOT EDIT.

package authz

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Authorize implements authorize operation.
	//
	// Ops-tier authorization decision for Oathkeeper's remote_json authorizer.
	//
	// POST /authorize
	Authorize(ctx context.Context, req *AuthorizeRequest) (AuthorizeRes, error)
	// CreateOperator implements createOperator operation.
	//
	// Create an operator identity and grant the operator role.
	//
	// POST /operators
	CreateOperator(ctx context.Context, req *OperatorInput) (*Operator, error)
	// GetIdentity implements getIdentity operation.
	//
	// Fetch one identity by id.
	//
	// GET /identities/{id}
	GetIdentity(ctx context.Context, params GetIdentityParams) (*Identity, error)
	// ListIdentities implements listIdentities operation.
	//
	// List identities (product users and operators) from Kratos, paginated.
	//
	// GET /identities
	ListIdentities(ctx context.Context, params ListIdentitiesParams) ([]Identity, error)
	// UpdateIdentity implements updateIdentity operation.
	//
	// Update an identity's editable traits.
	//
	// PUT /identities/{id}
	UpdateIdentity(ctx context.Context, req *IdentityUpdate, params UpdateIdentityParams) (*Identity, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
