#!/usr/bin/env bash
# Adopt this template as a project, for a repository created by the forge's "Use this template" (ADR-0106, ADR-0003).

set -euo pipefail
# shellcheck source=lib/log.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/log.sh"

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Where `copier update` fetches the template from. Hard-coded for the same reason
# `project-rename.sh` hard-codes the registry it replaces: the value names this
# repository, and the script that carries it does not survive into the project.
TEMPLATE_SRC="https://github.com/tabmadi/sovereign-platform-template.git"
VERSION_FILE=".template-version"

ref=""
args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
  --ref)
    [ "$#" -ge 2 ] || fail "--ref needs a value"
    ref="$2"
    shift 2
    ;;
  *)
    args+=("$1")
    shift
    ;;
  esac
done

[ "${#args[@]}" -eq 5 ] ||
  fail "usage: project-init.sh <project-name> <slug> <module-path> <apex-host> <image-registry> [--ref <template-ref>]"
project_name="${args[0]}" slug="${args[1]}" module="${args[2]}" apex="${args[3]}" registry="${args[4]}"

[ -f .copier-answers.yml ] &&
  fail "this project has already been initialised — .copier-answers.yml exists"

# ADR-0003's grammar, checked here as well as by `lint:naming` afterwards. Copier
# states the same rule in its own validator; a name is cheapest to reject before it
# reaches a provider console, and both entry points have to reject it.
[[ "$slug" =~ ^[a-z][a-z0-9]*(-[a-z0-9]+)*$ ]] ||
  fail "a slug is lower-case alphanumeric with single hyphens: ${slug}"
[ "${#slug}" -ge 6 ] && [ "${#slug}" -le 11 ] ||
  fail "a project slug is 6-11 characters: ${slug}"

# This becomes `_commit`, the baseline every future update merges against. A wrong value is worse than an absent one, so there is no guess.
if [ -z "$ref" ]; then
  [ -f "$VERSION_FILE" ] ||
    fail "no ${VERSION_FILE} in this tree and no --ref given

${VERSION_FILE} is written by a release. A copy taken between releases does not
carry one, so name the template commit or tag this repository was created from:

    mise run project:init -- ${project_name} ${slug} ${module} ${apex} ${registry} --ref <sha-or-tag>

It is listed at ${TEMPLATE_SRC%.git}/commits"
  ref="$(tr -d '[:space:]' <"$VERSION_FILE")"
  [ -n "$ref" ] || fail "${VERSION_FILE} is empty"
  detail "template ref from ${VERSION_FILE}: ${ref}"
fi

step "initialising ${project_name} from ${ref}"

# Runs before the answers file exists, which is also the order Copier uses. The
# rename carries its own guards against running in the template or running twice.
bash scripts/project-rename.sh "$slug" "$module" "$apex" "$registry"

# The field order matches Copier's own output, so a later `copier update` rewrites this file with no spurious diff.
cat >.copier-answers.yml <<EOF
# Generated by Copier — do not edit by hand (ADR-0106).
#
# \`_commit\` is this project's pin on the template, which is what makes the
# template a dependency like any other: Renovate proposes the bump, \`copier
# update\` applies it as a 3-way merge, and the project's own gates judge the
# result.
_commit: ${ref}
_src_path: ${TEMPLATE_SRC}
apex_host: ${apex}
image_registry: ${registry}
module_path: ${module}
project_name: ${project_name}
project_slug: ${slug}
EOF
detail "wrote .copier-answers.yml"

# What Copier's `_exclude` drops at render time, plus the two scripts that run once.
# This script goes last: unlinking a file bash is executing is safe, rewriting one in place is not. Nothing may follow these two lines.
rm -f copier.yml .copier-answers.yml.jinja "$VERSION_FILE" scripts/project-rename.sh
ok "initialised ${project_name} — run 'mise run gen' and 'mise run check' before the first commit"
rm -f -- "${BASH_SOURCE[0]}"
