/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all orders. */
        get: operations["listOrders"];
        put?: never;
        /**
         * @description Starts the Checkout Temporal saga, per ADR-0302. It is idempotent on the
         *     Idempotency-Key header: a retry of the same request returns the order that the
         *     first one created and does not place a second order.
         */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch an order by id. */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel an order. Starts the CancelOrder workflow, per ADR-0302. */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject-data/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One page of the identities that own orders, in identity order. */
        get: operations["listOrderSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject-data/orders/{identity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every order that the subject placed. */
        get: operations["exportOrdersSubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject-data/orders/{identity_id}/erase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Anonymise the owner of the subject's orders. The orders stay, because they
         *     carry a bookkeeping obligation. Safe to run again.
         */
        post: operations["eraseOrdersSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457 problem details. Services and the edge both serve it as
         *     `application/problem+json`, so a generated client has one error branch, not two.
         * @example {
         *       "type": "about:blank",
         *       "title": "Not Found",
         *       "status": 404,
         *       "detail": "No product with that identifier.",
         *       "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736"
         *     }
         */
        Problem: {
            /**
             * @description `about:blank`, except where two errors share a status code and a client
             *     handles them differently. That case uses a `urn:problem-type:<service>:<slug>`
             *     URN. It is never a dereferenceable URL, which would put an error taxonomy into
             *     the flat public URL namespace.
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * @description A stable, human-readable summary. It does not change with the instance.
             * @example Not Found
             */
            title: string;
            /**
             * @description The HTTP status, repeated in the body.
             * @example 404
             */
            status: number;
            /**
             * @description Specific to the instance and safe to show a user. Never a stack trace, a query,
             *     or an internal hostname.
             * @example No product with that identifier.
             */
            detail?: string;
            /**
             * @description The W3C Trace Context trace-id of the failing request, so an error that a user
             *     reports leads to its trace. The active span supplies it, not the handler.
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string;
            /**
             * @description Field-level validation failures, filled from the generated validator.
             *     Absent when the failure is not a validation failure.
             */
            errors?: {
                /**
                 * @description RFC 6901 JSON Pointer to the member that failed.
                 * @example /price/amount
                 */
                pointer: string;
                /** @example must be a decimal amount */
                message: string;
            }[];
        };
        /**
         * @description A monetary amount. The amount is a decimal string, because a JSON number becomes
         *     a double in the TypeScript client, and a double cannot hold a decimal amount
         *     exactly. The currency goes with the amount, because an amount without one is
         *     not a quantity of anything.
         * @example {
         *       "amount": "1299.00",
         *       "currency": "EUR"
         *     }
         */
        Money: {
            /**
             * @description Decimal amount, with a leading sign when negative. No thousands separators.
             * @example 1299.00
             */
            amount: string;
            /**
             * @description ISO 4217 alphabetic code, uppercase.
             * @example EUR
             */
            currency: string;
        };
        /**
         * @description An order identifier: `order_` and the UUIDv7 in 26 characters of Crockford
         *     base32. The first character is at most 7, because 26 characters hold 130 bits and
         *     a UUID has 128. It is opaque to a consumer: nothing parses, orders, or builds one.
         * @example order_01kztnj6c8e0jt7vzw0cn1wxvd
         */
        OrderId: string;
        /**
         * @description A product identifier: `product_` and the UUIDv7 in 26 characters of Crockford
         *     base32. It is opaque to a consumer: nothing parses, orders, or builds one.
         * @example product_01kztmx9e0fq1r13w5d1aerqw6
         */
        ProductId: string;
        /**
         * @description Handle to an async Temporal workflow run.
         * @example {
         *       "id": "checkout-order_01kztnj6c8e0jt7vzw0cn1wxvd",
         *       "run_id": "019a3f8c-6d21-7c4b-8e55-0f27f7f0e001",
         *       "status": "running",
         *       "result_url": "/api/orders/order_01kztnj6c8e0jt7vzw0cn1wxvd"
         *     }
         */
        WorkflowHandle: {
            id: string;
            run_id: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "cancelled";
            /**
             * Format: uri-reference
             * @description GET it to fetch the terminal status and result
             */
            result_url?: string;
        };
        /** @description Request body to start a checkout. */
        CheckoutInput: {
            product_id: components["schemas"]["ProductId"];
            quantity: number;
        };
        /**
         * @description One page of subjects. `next` is absent on the last page.
         * @example {
         *       "subjects": [
         *         "0b6f6f2e-5d3b-4f39-9a5e-3c7a1d1e2f40"
         *       ],
         *       "next": "0b6f6f2e-5d3b-4f39-9a5e-3c7a1d1e2f40"
         *     }
         */
        SubjectPage: {
            subjects: string[];
            /** @description The cursor for the next page. */
            next?: string;
        };
        /** @description The value that replaces the identity in every row. The workflow chooses one per erasure. */
        ErasureRequest: {
            pseudonym: string;
        };
        /**
         * @description The rows that the erasure changed.
         * @example {
         *       "rows": 3
         *     }
         */
        ErasureResult: {
            rows: number;
        };
        /**
         * @description A subject's orders.
         * @example {
         *       "orders": [
         *         {
         *           "id": "order_01kztnj6c8e0jt7vzw0cn1wxvd",
         *           "product_id": "product_01kztmx9e0fq1r13w5d1aerqw6",
         *           "quantity": 2,
         *           "total": {
         *             "amount": "2598.00",
         *             "currency": "EUR"
         *           },
         *           "status": "confirmed"
         *         }
         *       ]
         *     }
         */
        SubjectOrders: {
            orders: components["schemas"]["Order"][];
        };
        /**
         * @description A customer order.
         * @example {
         *       "id": "order_01kztnj6c8e0jt7vzw0cn1wxvd",
         *       "product_id": "product_01kztmx9e0fq1r13w5d1aerqw6",
         *       "quantity": 2,
         *       "total": {
         *         "amount": "2598.00",
         *         "currency": "EUR"
         *       },
         *       "status": "confirmed"
         *     }
         */
        Order: {
            id: components["schemas"]["OrderId"];
            product_id: components["schemas"]["ProductId"];
            quantity: number;
            total: components["schemas"]["Money"];
            /** @enum {string} */
            status: "pending" | "confirmed" | "failed" | "cancelled";
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The order list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated key that makes the checkout idempotent. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description The checkout to start. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order id. */
                id: components["schemas"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the order to cancel. */
                id: components["schemas"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listOrderSubjects: {
        parameters: {
            query?: {
                /** @description The last identity of the previous page. */
                after?: string;
                /** @description The page size. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportOrdersSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Kratos identity. */
                identity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subject's orders. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOrders"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    eraseOrdersSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Kratos identity. */
                identity_id: string;
            };
            cookie?: never;
        };
        /** @description The replacement for the identity. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ErasureRequest"];
            };
        };
        responses: {
            /** @description The rows that changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
