// Code generated by ogen, DO NOT EDIT.

package analytics

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ComputeFunnelRollup implements computeFunnelRollup operation.
	//
	// Recompute a funnel's rollup over a window, one bucket per day.
	//
	// Idempotent by construction: a bucket is replaced rather than added to, so re-running over a window
	// that is still filling is the normal case rather than a hazard. The most recent bucket is always
	// incomplete.
	//
	// POST /analytics/funnels/{funnel}/rollup
	ComputeFunnelRollup(ctx context.Context, req *RollupWindow, params ComputeFunnelRollupParams) (*RollupResult, error)
	// GetConsent implements getConsent operation.
	//
	// Read the recorded decision for a session.
	//
	// GET /analytics/consent
	GetConsent(ctx context.Context, params GetConsentParams) (*Consent, error)
	// GetFunnelRollup implements getFunnelRollup operation.
	//
	// Read a funnel's computed rollup, in bucket then step order.
	//
	// GET /analytics/funnels/{funnel}/rollup
	GetFunnelRollup(ctx context.Context, params GetFunnelRollupParams) ([]FunnelRollupRow, error)
	// RecordConsent implements recordConsent operation.
	//
	// Record or withdraw consent for a session.
	//
	// PUT /analytics/consent
	RecordConsent(ctx context.Context, req *ConsentInput) (*Consent, error)
	// RecordEvents implements recordEvents operation.
	//
	// Record a batch of marketing events.
	//
	// POST /analytics/events
	RecordEvents(ctx context.Context, req *EventBatch) (*RecordResult, error)
	// SummariseEvents implements summariseEvents operation.
	//
	// Event counts over a window, the aggregate every funnel question starts from.
	//
	// GET /analytics/summary
	SummariseEvents(ctx context.Context, params SummariseEventsParams) ([]EventSummary, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
