// Code generated by ogen, DO NOT EDIT.

package analytics

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ApplyAnalyticsRetention implements applyAnalyticsRetention operation.
	//
	// Create the event partitions for this month and the next, and drop the partitions that are past
	// retention. An event row holds a `device` column, and that class is kept for 90 days. So a month is
	// dropped when it ended more than 90 days ago. Safe to run again: each step checks what exists.
	//
	// POST /analytics/retention
	ApplyAnalyticsRetention(ctx context.Context) (*RetentionResult, error)
	// ComputeFunnelRollup implements computeFunnelRollup operation.
	//
	// Recompute a funnel's rollup over a window, one bucket per day.
	//
	// Idempotent by design: a bucket is replaced and not added to. So a new run over a window that is
	// still filling is normal and safe. The most recent bucket is always incomplete.
	//
	// POST /analytics/funnels/{funnel}/rollup
	ComputeFunnelRollup(ctx context.Context, req *RollupWindow, params ComputeFunnelRollupParams) (*RollupResult, error)
	// EraseAnalyticsSubject implements eraseAnalyticsSubject operation.
	//
	// Anonymise the subject's identifiers and delete the free text and device class of their events. Safe
	// to run again: a second call finds nothing to change.
	//
	// POST /subject-data/analytics/{identity_id}/erase
	EraseAnalyticsSubject(ctx context.Context, req *ErasureRequest, params EraseAnalyticsSubjectParams) (*AnalyticsErasure, error)
	// ExportAnalyticsSubject implements exportAnalyticsSubject operation.
	//
	// Every event and consent record of every session that the subject is known in.
	//
	// GET /subject-data/analytics/{identity_id}
	ExportAnalyticsSubject(ctx context.Context, params ExportAnalyticsSubjectParams) (*SubjectAnalytics, error)
	// GetConsent implements getConsent operation.
	//
	// Read the recorded decision for a session.
	//
	// GET /analytics/consent
	GetConsent(ctx context.Context, params GetConsentParams) (*Consent, error)
	// GetFunnelRollup implements getFunnelRollup operation.
	//
	// Read a funnel's computed rollup, in bucket and then step order.
	//
	// GET /analytics/funnels/{funnel}/rollup
	GetFunnelRollup(ctx context.Context, params GetFunnelRollupParams) ([]FunnelRollupRow, error)
	// ListAnalyticsSubjects implements listAnalyticsSubjects operation.
	//
	// One page of the identities that this store holds data for, in identity order.
	//
	// GET /subject-data/analytics
	ListAnalyticsSubjects(ctx context.Context, params ListAnalyticsSubjectsParams) (*SubjectPage, error)
	// RecordConsent implements recordConsent operation.
	//
	// Record or withdraw consent for a session.
	//
	// PUT /analytics/consent
	RecordConsent(ctx context.Context, req *ConsentInput) (*Consent, error)
	// RecordEvents implements recordEvents operation.
	//
	// Record a batch of marketing events.
	//
	// POST /analytics/events
	RecordEvents(ctx context.Context, req *EventBatch) (*RecordResult, error)
	// SummariseEvents implements summariseEvents operation.
	//
	// Event counts over a window. Every funnel question starts from this aggregate.
	//
	// GET /analytics/summary
	SummariseEvents(ctx context.Context, params SummariseEventsParams) ([]EventSummary, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
