// Code generated by ogen, DO NOT EDIT.

package analytics

// OperationName is the ogen operation name
type OperationName = string

const (
	ApplyAnalyticsRetentionOperation OperationName = "ApplyAnalyticsRetention"
	ComputeFunnelRollupOperation     OperationName = "ComputeFunnelRollup"
	EraseAnalyticsSubjectOperation   OperationName = "EraseAnalyticsSubject"
	ExportAnalyticsSubjectOperation  OperationName = "ExportAnalyticsSubject"
	GetConsentOperation              OperationName = "GetConsent"
	GetFunnelRollupOperation         OperationName = "GetFunnelRollup"
	ListAnalyticsSubjectsOperation   OperationName = "ListAnalyticsSubjects"
	RecordConsentOperation           OperationName = "RecordConsent"
	RecordEventsOperation            OperationName = "RecordEvents"
	SummariseEventsOperation         OperationName = "SummariseEvents"
)
