// Code generated by ogen, DO NOT EDIT.

package analytics

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ComputeFunnelRollup implements computeFunnelRollup operation.
//
// Recompute a funnel's rollup over a window, one bucket per day.
//
// Idempotent by construction: a bucket is replaced rather than added to, so re-running over a window
// that is still filling is the normal case rather than a hazard. The most recent bucket is always
// incomplete.
//
// POST /analytics/funnels/{funnel}/rollup
func (UnimplementedHandler) ComputeFunnelRollup(ctx context.Context, req *RollupWindow, params ComputeFunnelRollupParams) (r *RollupResult, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConsent implements getConsent operation.
//
// Read the recorded decision for a session.
//
// GET /analytics/consent
func (UnimplementedHandler) GetConsent(ctx context.Context, params GetConsentParams) (r *Consent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFunnelRollup implements getFunnelRollup operation.
//
// Read a funnel's computed rollup, in bucket then step order.
//
// GET /analytics/funnels/{funnel}/rollup
func (UnimplementedHandler) GetFunnelRollup(ctx context.Context, params GetFunnelRollupParams) (r []FunnelRollupRow, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordConsent implements recordConsent operation.
//
// Record or withdraw consent for a session.
//
// PUT /analytics/consent
func (UnimplementedHandler) RecordConsent(ctx context.Context, req *ConsentInput) (r *Consent, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordEvents implements recordEvents operation.
//
// Record a batch of marketing events.
//
// POST /analytics/events
func (UnimplementedHandler) RecordEvents(ctx context.Context, req *EventBatch) (r *RecordResult, _ error) {
	return r, ht.ErrNotImplemented
}

// SummariseEvents implements summariseEvents operation.
//
// Event counts over a window, the aggregate every funnel question starts from.
//
// GET /analytics/summary
func (UnimplementedHandler) SummariseEvents(ctx context.Context, params SummariseEventsParams) (r []EventSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
