name: orgs
image:
  repository: ghcr.io/tabmadi/microservices-monorepo-template/orgs-server
  tag: "0000000000000000000000000000000000000000"
worker: { enabled: false }
server:  { replicas: 1 }
ingress: { enabled: true, host: dev.example.com }
secrets: { envFrom: [orgs-db-creds] }
